salesforce-litle-MP/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Litle_MID__c</fullName>
        <description>Merchant Identifer</description>
        <label>Litle MID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PayFac_Portal_Link__c</fullName>
        <label>PayFac Portal Link</label>
        <type>Url</type>
    </fields>
</CustomObject>

salesforce-litle-MP/src/objects/Litle_Business__c.object
<CustomObject>
    <fields>
        <fullName>Litle_KYC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Litle KYC</label>
        <referenceTo>Litle_KYC__c</referenceTo>
        <relationshipLabel>Litle Business</relationshipLabel>
        <relationshipName>Litle_Business</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Litle Business</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle Business Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/Litle_KYC__c.object
<CustomObject>
    <label>Litle KYC</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle KYC Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle KYC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/Litle_Principal__c.object
<CustomObject>
    <description>Stores the principal details of the KYC information</description>
    <fields>
        <fullName>Litle_KYC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent KYC of the Principal</description>
        <inlineHelpText>Parent KYC of the Principal</inlineHelpText>
        <label>Litle KYC</label>
        <referenceTo>Litle_KYC__c</referenceTo>
        <relationshipLabel>Litle Principals</relationshipLabel>
        <relationshipName>Litle_Principals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Litle Principal</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle Principal Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Principals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/Litle_Risk_Indicator__c.object
<CustomObject>
    <fields>
        <fullName>Litle_Verification_Result__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Litle Verification Result</label>
        <referenceTo>Litle_Verification_Result__c</referenceTo>
        <relationshipLabel>Litle Risk Indicators</relationshipLabel>
        <relationshipName>Litle_Risk_Indicators</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Litle Risk Indicator</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle Risk Indicator Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Risk Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/Litle_Verification_Result__c.object
<CustomObject>
    <fields>
        <fullName>Litle_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Litle Business</label>
        <referenceTo>Litle_Business__c</referenceTo>
        <relationshipLabel>Litle Verification Result</relationshipLabel>
        <relationshipName>Litle_Verification_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Litle_Principal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Litle Principal</label>
        <referenceTo>Litle_Principal__c</referenceTo>
        <relationshipLabel>Litle Verification Result</relationshipLabel>
        <relationshipName>Litle_Verification_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Litle Verification Result</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle Verification Result Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Verification Result</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/LitleMappingsSaveLog__c.object
<CustomObject>
    <description>Object to log saves of the Litle Mapping</description>
    <label>LitleMappingsSaveLog</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>LogId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LitleMappingsSaveLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/LitleRequestResponseLog__c.object
<CustomObject>
    <description>Object to log all the requests and responses to Litle MP</description>
    <label>Litle Request Response Log</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>LogId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Request Response Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/SalesforceLitleMappingsObject__c.object
<CustomObject>
    <description>Salesforce and Litle&apos;s field mappings object</description>
    <label>SalesforceLitleMappingsObject</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesforceLitleMappingsObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/classes/ResetService.cls
/*
Copyright (c) 2013 Litle & Co.
Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:
The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/
public class ResetService {
	
	public void deleteAllLitleKYC(){
		List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c];
		for(Litle_KYC__c litleKYC : litleKYCs){
			deleteBusinessOfKYC(litleKYC.Id);
			deletePrincipalOfKYC(litleKYC.Id);
			delete litleKYC;
		}
	}
	
	public void deleteBusinessVerificationResult(String businessId){
		if(String.isNotEmpty(businessId)){
			List<Litle_Verification_Result__c> verificationResults = [select Id, Name from Litle_Verification_Result__c where Litle_Business__c =:businessId];
			for(Litle_Verification_Result__c verificationResult : verificationResults){
				deleteRiskIndicatorOfVerificationResult(verificationResult.Id);
				delete verificationResult;
			}
		}	
	}
	
	public void deleteRiskIndicatorOfVerificationResult(String verificationResultId){
		if(String.isNotEmpty(verificationResultId)){
			List<Litle_Risk_Indicator__c> riskIndicators = [select Id, Name from Litle_Risk_Indicator__c where Litle_Verification_Result__c =:verificationResultId];
			for(Litle_Risk_Indicator__c riskIndicator : riskIndicators){
				delete riskIndicator;
			}
		}
	}
	
	public void deletePrincipalVerificationResult(String principalId){
		if(String.isNotEmpty(principalId)){
			List<Litle_Verification_Result__c> verificationResults = [select Id, Name from Litle_Verification_Result__c where Litle_Principal__c =:principalId];
			for(Litle_Verification_Result__c verificationResult : verificationResults){
				deleteRiskIndicatorOfVerificationResult(verificationResult.Id);
				delete verificationResult;
			}
		}	
	}
	
	public void deleteBusinessOfKYC(String litleKYCId){
		if(String.isNotEmpty(litleKYCId)){
			List<Litle_Business__c> businesses = [select Id, Name from Litle_Business__c where Litle_KYC__c =:litleKYCId];
			for(Litle_Business__c business: businesses){
				deleteBusinessVerificationResult(business.Id);
				delete business;
			}
		}
	}
	
	public void deletePrincipalOfKYC(String litleKYCId){
		if(String.isNotEmpty(litleKYCId)){
			List<Litle_Principal__c> principals = [select Id, Name from Litle_Principal__c where Litle_KYC__c =:litleKYCId];
			for(Litle_Principal__c principal: principals){
				deletePrincipalVerificationResult(principal.Id);
				delete principal;
			}
		}	
	}
	
	public void deleteAllLitleMappingsSaveLogs(){
		List<LitleMappingsSaveLog__c> litleMappingsSaveLogsToBeDeleted = [select Id, Name from LitleMappingsSaveLog__c];
		delete litleMappingsSaveLogsToBeDeleted;		
	}
	
	public void deleteAllLitleRequestResponseLogs(){
		List<LitleRequestResponseLog__c> LitleRequestResponseLogsToBeDeleted = [select Id, Name from LitleRequestResponseLog__c];
		delete litleRequestResponseLogsToBeDeleted;
	}
	
	public void deleteAllSalesforceLitleMappingsObjects(){
		List<SalesforceLitleMappingsObject__c> mappingObjectsToBeDeleted = [select Id, Name from SalesforceLitleMappingsObject__c];
		delete mappingObjectsToBeDeleted;
	}
	
	public void deleteAllCasesOfAccount(String accountId){
		if(String.isNotEmpty(accountId)){
			List<Case> accountCases = [select Id from Case where AccountId =:accountId];
			delete accountCases;
		}
	}
	
	public void deleteAllAccounts(){
		List<Account> accountsToBeDeleted = [select Id, Name from Account];
		for(Account accountToBeDeleted : accountsToBeDeleted){
			deleteAllCasesOfAccount(accountToBeDeleted.Id);
			delete accountToBeDeleted;
		}
	}
	
	public void deleteAllOpportunities(){
		List<Opportunity> opportunitiesToBeDeleted = [select Id, Name from Opportunity];
		for(Opportunity opportunityToBeDeleted : opportunitiesToBeDeleted){
			delete opportunityToBeDeleted;	
		}
	}
	
	public void createDefaultAccount(){
		Account account = new Account();
		account.PayFac_Portal_Link__c = null;
    	account.Litle_MID__c = null;
    	account.Website = 'http://www.pyramid.com';
    	account.Type = 'Customer - Channel';
    	account.TickerSymbol = 'PYR';
    	account.Sic = '4253';
		account.ShippingStreet = '2 Place Jussieu';
		account.ShippingState = null;
		account.ShippingCity = 'Paris';
		account.ShippingPostalCode = '75251';
		account.ShippingCountry = 'France';
		account.Ownership = 'Private';
		account.Rating = 'Warm';
		account.Active__c = 'Yes';
		account.SLAExpirationDate__c = Date.today();
		account.UpsellOpportunity__c = 'Maybe';
		account.SLA__c = 'Silver';
		account.Description = 'This is a demo Account';
		account.Phone = '(014) 427-4427';
		account.Name = 'Pyramid Construction Inc';
		account.Industry = 'Construction';
		account.Fax = '(014) 427-4428';
		account.BillingStreet = '2 Place Jussieu';
		account.BillingState = null;
		account.BillingPostalCode = '75251';
		account.BillingCountry = 'France';
		account.BillingCity = 'Paris';
		account.AnnualRevenue = 950000000;
		insert account;
	}
	
	public void createDefaultOpportunity(){
		Opportunity opportunity = new Opportunity();
		opportunity.PayFac_Portal_Link__c = null;
    	opportunity.Litle_MID__c = null;
    	opportunity.DeliveryInstallationStatus__c = 'In progress';
    	opportunity.Type = 'New Customer';
    	opportunity.StageName = 'Prospecting';
    	opportunity.Probability = 10;
    	opportunity.Name = 'Pyramid Construction Lowell Branch';
		opportunity.LeadSource = 'Web';
		opportunity.Description = 'This is a demo Opportunity';
		opportunity.CloseDate = Date.today();
		insert opportunity;
	}
}