salesforce-litle-MP/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Litle_MID__c</fullName>
        <description>Merchant Identifer</description>
        <label>Litle MID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PayFac_Portal_Link__c</fullName>
        <label>PayFac Portal Link</label>
        <type>Url</type>
    </fields>
</CustomObject>

salesforce-litle-MP/src/objects/SalesforceLitleMappingsObject__c.object
<CustomObject>
    <description>Salesforce and Litle&apos;s field mappings object</description>
    <fields>
        <fullName>legalEntityAnnualCreditCardSalesVolumeX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityAnnualCreditCardSalesVolumeX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityAnnualCreditCardSalesVolume__c</fullName>
        <description>Legal Entity AnnualCreditCardSalesVolume</description>
        <label>legalEntityAnnualCreditCardSalesVolume</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityCityX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityCityX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityCity__c</fullName>
        <description>Legal Entity City</description>
        <label>legalEntityCity</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityContactPhoneX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityContactPhoneX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityContactPhone__c</fullName>
        <description>Legal Entity ContactPhone</description>
        <label>legalEntityContactPhone</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityCountryCodeX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityCountryCodeX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityCountryCode__c</fullName>
        <description>Legal Entity CountryCode</description>
        <label>legalEntityCountryCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityHasAcceptedCreditCardsD__c</fullName>
        <description>Legal Entity HasAcceptedCreditCardsD</description>
        <label>legalEntityHasAcceptedCreditCardsDefault</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityHasAcceptedCreditCardsX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityHasAcceptedCreditCardsX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityNameX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityNameX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityName__c</fullName>
        <description>Legal Entity Name</description>
        <label>legalEntityName</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPostalCodeX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityPostalCodeX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityPostalCode__c</fullName>
        <description>Legal Entity PostalCode</description>
        <label>legalEntityPostalCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalCityX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityPrincipalCityX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalCity__c</fullName>
        <description>Legal Entity City</description>
        <label>legalEntityPrincipalCity</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalContactPhoneX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityPrincipalContactPhoneX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalContactPhone__c</fullName>
        <description>Legal Entity ContactPhone</description>
        <label>legalEntityPrincipalContactPhone</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalCountryCodeX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityPrincipalCountryCodeX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalCountryCode__c</fullName>
        <description>Legal Entity CountryCode</description>
        <label>legalEntityPrincipalCountryCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalFirstNameD__c</fullName>
        <description>Legal Entity Principal FirstNameD</description>
        <label>legalEntityPrincipalFirstNameD</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalFirstNameX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityPrincipalFirstNameX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalLastNameD__c</fullName>
        <description>Legal Entity Principal LastNameD</description>
        <label>legalEntityPrincipalLastNameD</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalLastNameX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityPrincipalLastNameX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalPostalCodeX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityPrincipalPostalCodeX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalPostalCode__c</fullName>
        <description>Legal Entity PostalCode</description>
        <label>legalEntityPrincipalPostalCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalStateProvinceX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityPrincipalStateProvinceX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalStateProvince__c</fullName>
        <description>Legal Entity StateProvince</description>
        <label>legalEntityPrincipalStateProvince</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalStreetAddress1X__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityPrincipalStreetAddress1X</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalStreetAddress1__c</fullName>
        <description>Legal Entity StreetAddress1</description>
        <label>legalEntityPrincipalStreetAddress1</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityStateProvinceX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityStateProvinceX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityStateProvince__c</fullName>
        <description>Legal Entity StateProvince</description>
        <label>legalEntityStateProvince</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityStreetAddress1X__c</fullName>
        <defaultValue>false</defaultValue>
        <label>legalEntityStreetAddress1X</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>legalEntityStreetAddress1__c</fullName>
        <description>Legal Entity StreetAddress1</description>
        <label>legalEntityStreetAddress1</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityTypeD__c</fullName>
        <description>Legal Entity TypeD</description>
        <label>legalEntityTypeD</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>litleEnvironment__c</fullName>
        <description>Stores the environment for MP</description>
        <label>Litle Environment</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>merchantUsername__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Merchant username for Litle requests</description>
        <label>merchantUsername</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>subMerchantCityX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>subMerchantCityX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subMerchantCity__c</fullName>
        <description>Sub Merchant City</description>
        <label>subMerchantCity</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantCountryCodeX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>subMerchantCountryCodeX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subMerchantCountryCode__c</fullName>
        <description>Sub Merchant CountryCode</description>
        <label>subMerchantCountryCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantCustomerServiceNumberX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>subMerchantCustomerServiceNumberX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subMerchantCustomerServiceNumber__c</fullName>
        <description>Sub Merchant CustomerServiceNumber</description>
        <label>subMerchantCustomerServiceNumber</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantFirstNameD__c</fullName>
        <description>Sub Merchant FirstNameD</description>
        <label>subMerchantFirstNameDefault</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantFirstNameX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>subMerchantFirstNameX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subMerchantHardCodeBillingDescriptorX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>subMerchantHardCodeBillingDescriptorX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subMerchantHardCodeBillingDescriptor__c</fullName>
        <description>Sub Merchant HardCodeBillingDescriptor</description>
        <label>subMerchantHardCodeBillingDescriptor</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantLastNameD__c</fullName>
        <description>Sub Merchant LastNameD</description>
        <label>subMerchantLastNameDefault</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantLastNameX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>subMerchantLastNameX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subMerchantMaxTransactionAmountX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>subMerchantMaxTransactionAmountX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subMerchantMaxTransactionAmount__c</fullName>
        <description>Sub Merchant MaxTransactionAmount</description>
        <label>subMerchantMaxTransactionAmount</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantMerchantCategoryCodeD__c</fullName>
        <description>Sub Merchant MerchantCategoryCodeD</description>
        <label>subMerchantMerchantCategoryCodeDefault</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantMerchantCategoryCodeX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>subMerchantMerchantCategoryCodeX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subMerchantMerchantNameX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>subMerchantMerchantNameX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subMerchantMerchantName__c</fullName>
        <description>Sub Merchant MerchantName</description>
        <label>subMerchantMerchantName</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantPhoneX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>subMerchantPhoneX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subMerchantPhone__c</fullName>
        <description>Sub Merchant Phone</description>
        <label>subMerchantPhone</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantPostalCodeX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>subMerchantPostalCodeX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subMerchantPostalCode__c</fullName>
        <description>Sub Merchant PostalCode</description>
        <label>subMerchantPostalCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantPspMerchantIdX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>subMerchantPspMerchantIdX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subMerchantPspMerchantId__c</fullName>
        <description>Sub Merchant PspMerchantId</description>
        <label>subMerchantPspMerchantId</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantStateProvinceX__c</fullName>
        <defaultValue>false</defaultValue>
        <label>subMerchantStateProvinceX</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subMerchantStateProvince__c</fullName>
        <description>Sub Merchant StateProvince</description>
        <label>subMerchantStateProvince</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantStreetAddress1X__c</fullName>
        <defaultValue>false</defaultValue>
        <label>subMerchantStreetAddress1X</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>subMerchantStreetAddress1__c</fullName>
        <description>Sub Merchant StreetAddress1</description>
        <label>subMerchantStreetAddress1</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>SalesforceLitleMappingsObject</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesforceLitleMappingsObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/classes/ResetControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ResetControllerTest {

    static testMethod void resetAll() {
        ResetController controller = new ResetController();
        controller.resetAll();
        List<Opportunity> opportunities = [Select o.AccountId, o.PayFac_Portal_Link__c, o.Litle_MID__c,
    							o.Type, o.StageName, o.Probability, o.Name, 
    							o.LeadSource, o.LastModifiedDate,  
    							o.Description, o.CloseDate
								From Opportunity o];
    	System.assertEquals(1, opportunities.size());
    	System.assertEquals(null, opportunities.get(0).PayFac_Portal_Link__c);
    	System.assertEquals(null, opportunities.get(0).Litle_MID__c);
    	System.assertEquals('New Customer', opportunities.get(0).Type);
    	System.assertEquals('Prospecting', opportunities.get(0).StageName);
    	System.assertEquals(10, opportunities.get(0).Probability);
    	System.assertEquals('Pyramid Construction Lowell Branch', opportunities.get(0).Name);
    	System.assertEquals('Web', opportunities.get(0).LeadSource);
    	System.assertEquals('This is a demo Opportunity', opportunities.get(0).Description);
    	
    	List<Account> accounts = [Select a.PayFac_Portal_Link__c, 
    								a.Litle_MID__c, a.Website, a.Type, 
    								a.TickerSymbol, a.Sic, a.ShippingStreet, 
    								a.ShippingState, a.ShippingPostalCode, 
    								a.Ownership, a.Rating, 
    								a.ShippingCountry, a.ShippingCity, a.Description,  a.Phone,
    								a.Name, a.Industry, a.Id, a.Fax, 
    								a.BillingStreet, a.BillingState, a.BillingPostalCode, 
    								a.BillingCountry, a.BillingCity, a.AnnualRevenue 
								From Account a];
    	System.assertEquals(1, accounts.size());
    	System.assertEquals(null, accounts.get(0).PayFac_Portal_Link__c);
    	System.assertEquals(null, accounts.get(0).Litle_MID__c);
    	System.assertEquals('http://www.pyramid.com', accounts.get(0).Website);
    	System.assertEquals('Customer - Channel', accounts.get(0).Type);
    	System.assertEquals('PYR', accounts.get(0).TickerSymbol);
    	System.assertEquals('4253', accounts.get(0).Sic);
    	System.assertEquals('900 Chelmsford St', accounts.get(0).ShippingStreet);
    	System.assertEquals('MA', accounts.get(0).ShippingState);
    	System.assertEquals('Lowell', accounts.get(0).ShippingCity);
    	System.assertEquals('01851', accounts.get(0).ShippingPostalCode);
    	System.assertEquals('USA', accounts.get(0).ShippingCountry);
    	System.assertEquals('Private', accounts.get(0).Ownership);
    	System.assertEquals('Warm', accounts.get(0).Rating);
    	System.assertEquals('This is a demo Account', accounts.get(0).Description);
    	System.assertEquals('(014) 427-4427', accounts.get(0).Phone);
    	System.assertEquals('Pyramid Construction Inc', accounts.get(0).Name);
    	System.assertEquals('Construction', accounts.get(0).Industry);
    	System.assertEquals('(014) 427-4428', accounts.get(0).Fax);
    	System.assertEquals('900 Chelmsford St', accounts.get(0).BillingStreet);
    	System.assertEquals('MA', accounts.get(0).BillingState);
    	System.assertEquals('01851', accounts.get(0).BillingPostalCode);
    	System.assertEquals('USA', accounts.get(0).BillingCountry);
    	System.assertEquals('Lowell', accounts.get(0).BillingCity);
    	System.assertEquals(950000000, accounts.get(0).AnnualRevenue);   
    	
    	
    	List<SalesforceLitleMappingsObject__c> mapObjects = [select merchantUsername__c ,
																litleEnvironment__c ,
																subMerchantPspMerchantId__c ,
														        subMerchantPspMerchantIdX__c ,
																subMerchantMerchantName__c ,
														        subMerchantMerchantNameX__c ,
														        subMerchantMerchantCategoryCodeD__c ,
														        subMerchantMerchantCategoryCodeX__c ,
														        subMerchantHardCodeBillingDescriptor__c ,
														        subMerchantHardCodeBillingDescriptorX__c ,
																subMerchantCustomerServiceNumber__c ,
														        subMerchantCustomerServiceNumberX__c ,
																subMerchantMaxTransactionAmount__c ,
														        subMerchantMaxTransactionAmountX__c ,
																subMerchantStateProvince__c ,
														        subMerchantStateProvinceX__c ,
														        subMerchantStreetAddress1__c,
														        subMerchantStreetAddress1X__c ,
														        subMerchantCity__c,
														        subMerchantCityX__c ,
														        subMerchantCountryCode__c,
														        subMerchantCountryCodeX__c ,
														        subMerchantPostalCode__c,
														        subMerchantPostalCodeX__c ,
														        legalEntityStateProvince__c,
																legalEntityStateProvinceX__c ,
																legalEntityStreetAddress1__c,
																legalEntityStreetAddress1X__c ,
																legalEntityCity__c,
																legalEntityCityX__c ,
														        legalEntityPostalCode__c,
																legalEntityPostalCodeX__c ,
																legalEntityCountryCode__c,
																legalEntityCountryCodeX__c ,
																legalEntityPrincipalCity__c,
																legalEntityPrincipalCityX__c ,
																legalEntityPrincipalCountryCode__c,
																legalEntityPrincipalCountryCodeX__c ,
																legalEntityPrincipalPostalCode__c,
																legalEntityPrincipalPostalCodeX__c ,
														        legalEntityPrincipalStateProvince__c,
																legalEntityPrincipalStateProvinceX__c ,
																legalEntityPrincipalStreetAddress1__c,
																legalEntityPrincipalStreetAddress1X__c ,
																legalEntityContactPhone__c ,
																legalEntityContactPhoneX__c ,
																legalEntityName__c ,
																legalEntityNameX__c ,
																legalEntityTypeD__c ,
																legalEntityHasAcceptedCreditCardsD__c,
																legalEntityHasAcceptedCreditCardsX__c,
																legalEntityAnnualCreditCardSalesVolume__c ,
																legalEntityAnnualCreditCardSalesVolumeX__c ,
																legalEntityPrincipalContactPhone__c ,
																legalEntityPrincipalContactPhoneX__c ,
																legalEntityPrincipalFirstNameD__c ,
																legalEntityPrincipalFirstNameX__c ,
																legalEntityPrincipalLastNameD__c ,
																legalEntityPrincipalLastNameX__c ,
														        subMerchantFirstNameD__c ,
														        subMerchantFirstNameX__c ,
														        subMerchantLastNameD__c ,
														        subMerchantLastNameX__c ,
														        subMerchantPhone__c ,
														        subMerchantPhoneX__c,
														        subMerchantEmailAddressD__c,
														        subMerchantEmailAddressX__c 
														        from SalesforceLitleMappingsObject__c];
    	/////////////
    	//THE FOLLOWING ASSERTS HAVE ACTUAL AND EXPECTED FLIPPED 
    	System.assertEquals(mapObjects.get(0).merchantUsername__c , 'PSPXMLV8');
		System.assertEquals(mapObjects.get(0).litleEnvironment__c , 'CERT');
		//psp sub merchant id - mapped to sf field
		System.assertEquals(mapObjects.get(0).subMerchantPspMerchantId__c , 'Account.Industry');
        System.assertEquals(mapObjects.get(0).subMerchantPspMerchantIdX__c , true);
		//merchant name - mapped to account name
		System.assertEquals(mapObjects.get(0).subMerchantMerchantName__c , 'Account.Name');
        System.assertEquals(mapObjects.get(0).subMerchantMerchantNameX__c , true);
		//merchant category code mapped to default value
        System.assertEquals(mapObjects.get(0).subMerchantMerchantCategoryCodeD__c , '7997');
        System.assertEquals(mapObjects.get(0).subMerchantMerchantCategoryCodeX__c , false);
		//default billing descriptor mapped to default value
        System.assertEquals(mapObjects.get(0).subMerchantHardCodeBillingDescriptor__c , 'Account.Industry');
        System.assertEquals(mapObjects.get(0).subMerchantHardCodeBillingDescriptorX__c , true);
		//customer service number mapped to account phone number
		System.assertEquals(mapObjects.get(0).subMerchantCustomerServiceNumber__c , 'Account.Phone');
        System.assertEquals(mapObjects.get(0).subMerchantCustomerServiceNumberX__c , true);
		//Max transaction amount mapped to opportunity 
		System.assertEquals(mapObjects.get(0).subMerchantMaxTransactionAmount__c , 'Account.AnnualRevenue');
        System.assertEquals(mapObjects.get(0).subMerchantMaxTransactionAmountX__c , true);
		//addresses mapped to account address
		System.assertEquals(mapObjects.get(0).subMerchantStateProvince__c , 'Account.BillingState');
        System.assertEquals(mapObjects.get(0).subMerchantStateProvinceX__c , true);
        System.assertEquals(mapObjects.get(0).subMerchantStreetAddress1__c, 'Account.BillingStreet');
        System.assertEquals(mapObjects.get(0).subMerchantStreetAddress1X__c , true);
        System.assertEquals(mapObjects.get(0).subMerchantCity__c, 'Account.BillingCity');
        System.assertEquals(mapObjects.get(0).subMerchantCityX__c , true);
        System.assertEquals(mapObjects.get(0).subMerchantCountryCode__c, 'Account.BillingCountry');
        System.assertEquals(mapObjects.get(0).subMerchantCountryCodeX__c , true);
        System.assertEquals(mapObjects.get(0).subMerchantPostalCode__c, 'Account.BillingPostalCode');
        System.assertEquals(mapObjects.get(0).subMerchantPostalCodeX__c , true);
        
        System.assertEquals(mapObjects.get(0).legalEntityStateProvince__c, 'Account.BillingState');
		System.assertEquals(mapObjects.get(0).legalEntityStateProvinceX__c , true);
		System.assertEquals(mapObjects.get(0).legalEntityStreetAddress1__c, 'Account.BillingStreet');
		System.assertEquals(mapObjects.get(0).legalEntityStreetAddress1X__c , true);
		System.assertEquals(mapObjects.get(0).legalEntityCity__c, 'Account.BillingCity');
		System.assertEquals(mapObjects.get(0).legalEntityCityX__c , true);
        System.assertEquals(mapObjects.get(0).legalEntityPostalCode__c, 'Account.BillingPostalCode');
		System.assertEquals(mapObjects.get(0).legalEntityPostalCodeX__c , true);
		System.assertEquals(mapObjects.get(0).legalEntityCountryCode__c, 'Account.BillingCountry');
		System.assertEquals(mapObjects.get(0).legalEntityCountryCodeX__c , true);
		System.assertEquals(mapObjects.get(0).legalEntityHasAcceptedCreditCardsD__c, 'false');
		System.assertEquals(mapObjects.get(0).legalEntityHasAcceptedCreditCardsX__c , false);
		
		
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalCity__c, 'Account.BillingCity');
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalCityX__c , true);
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalCountryCode__c, 'Account.BillingCountry');
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalCountryCodeX__c , true);
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalPostalCode__c, 'Account.BillingPostalCode');
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalPostalCodeX__c , true);
        System.assertEquals(mapObjects.get(0).legalEntityPrincipalStateProvince__c, 'Account.BillingState');
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalStateProvinceX__c , true);
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalStreetAddress1__c, 'Account.BillingStreet');
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalStreetAddress1X__c , true);
		
		
		System.assertEquals(mapObjects.get(0).legalEntityContactPhone__c , 'Account.Phone');
		System.assertEquals(mapObjects.get(0).legalEntityContactPhoneX__c , true);
		//legal entity name mapped to opportunity name
		System.assertEquals(mapObjects.get(0).legalEntityName__c , 'Account.Name');
		System.assertEquals(mapObjects.get(0).legalEntityNameX__c , true);
		//type individual sole
		System.assertEquals(mapObjects.get(0).legalEntityTypeD__c , 'Individual Sole Proprietorship');
		//annual credit card sales volume mapped to AnnualRevenue
		System.assertEquals(mapObjects.get(0).legalEntityAnnualCreditCardSalesVolume__c , 'Account.AnnualRevenue');
		System.assertEquals(mapObjects.get(0).legalEntityAnnualCreditCardSalesVolumeX__c , true);
		//first name,last name, phone from account
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalContactPhone__c , 'Account.Phone');
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalContactPhoneX__c , true);
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalFirstNameD__c , 'John');
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalFirstNameX__c , false);
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalLastNameD__c , 'Doe');
		System.assertEquals(mapObjects.get(0).legalEntityPrincipalLastNameX__c , false);
		
        System.assertEquals(mapObjects.get(0).subMerchantFirstNameD__c , 'John');
        System.assertEquals(mapObjects.get(0).subMerchantFirstNameX__c , false);
        System.assertEquals(mapObjects.get(0).subMerchantLastNameD__c , 'Doe');
        System.assertEquals(mapObjects.get(0).subMerchantLastNameX__c , false);
        System.assertEquals(mapObjects.get(0).subMerchantEmailAddressD__c , 'johnDoe@pyramid.com');
        System.assertEquals(mapObjects.get(0).subMerchantEmailAddressX__c , false);
        System.assertEquals(mapObjects.get(0).subMerchantPhone__c , 'Account.Phone');
        System.assertEquals(mapObjects.get(0).subMerchantPhoneX__c , true);
    }
}