salesforce-litle-MP/src/objects/LitleRequestResponseLog__c.object
<CustomObject>
    <description>Object to log all the requests and responses to Litle MP</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Origination Account of the log</description>
        <inlineHelpText>Origination Account of the log</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>LitleRequestResponseLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity causing this log entry</description>
        <inlineHelpText>Opportunity causing this log entry</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>LitleRequestResponseLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>createLegalEntityRequestDate__c</fullName>
        <description>Request date for create legal entity request</description>
        <inlineHelpText>Request date for create legal entity request</inlineHelpText>
        <label>Create LegalEntity  RequestDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>createLegalEntityRequestXml__c</fullName>
        <description>Create Legal Entity Request Xml</description>
        <inlineHelpText>Create Legal Entity Request Xml</inlineHelpText>
        <label>Create LegalEntity  RequestXml</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>createLegalEntityResponseDate__c</fullName>
        <description>Create Legal Entity Response Date</description>
        <inlineHelpText>Create Legal Entity Response Date</inlineHelpText>
        <label>Create LegalEntity  ResponseDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>createLegalEntityResponseStatusCode__c</fullName>
        <description>Create Legal Entity Response Status Code</description>
        <inlineHelpText>Create Legal Entity Response Status Code</inlineHelpText>
        <label>Create LegalEntity  ResponseStatusCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>createLegalEntityResponseStatusMessage__c</fullName>
        <description>Create Legal Entity Response Status Message</description>
        <inlineHelpText>Create Legal Entity Response Status Message</inlineHelpText>
        <label>Create LegalEntity  ResponseStatusMsg</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>createLegalEntityResponseXml__c</fullName>
        <description>Create Legal Entity Response Xml</description>
        <inlineHelpText>Create Legal Entity Response Xml</inlineHelpText>
        <label>Create LegalEntity  ResponseXml</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>createSubMerchantRequestDate__c</fullName>
        <description>Request date for create Sub Merchant request</description>
        <inlineHelpText>Request date for create Sub Merchant request</inlineHelpText>
        <label>Create SubMerchantRequestDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>createSubMerchantRequestXml__c</fullName>
        <description>Create Sub Merchant Request Xml</description>
        <inlineHelpText>Create Sub Merchant Request Xml</inlineHelpText>
        <label>Create SubMerchantRequestXml</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>createSubMerchantResponseDate__c</fullName>
        <description>Create Sub Merchant Response Date</description>
        <inlineHelpText>Create Sub Merchant Response Date</inlineHelpText>
        <label>Create SubMerchantResponseDate</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>createSubMerchantResponseStatusCode__c</fullName>
        <description>Create Sub Merchant Response Status Code</description>
        <inlineHelpText>Create Sub Merchant Response Status Code</inlineHelpText>
        <label>Create SubMerchantResponseStatusCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>createSubMerchantResponseStatusMessage__c</fullName>
        <description>Create Sub Merchant Response Status Message</description>
        <inlineHelpText>Create Sub Merchant Response Status Message</inlineHelpText>
        <label>Create SubMerchantResponseStatusMessage</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>createSubMerchantResponseXml__c</fullName>
        <description>Create Sub Merchant Response Xml</description>
        <inlineHelpText>Create Sub Merchant Response Xml</inlineHelpText>
        <label>Create SubMerchantResponseXml</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>legalEntityAcceptHeader__c</fullName>
        <description>Accept header for legal entity request</description>
        <inlineHelpText>Accept header for legal entity request</inlineHelpText>
        <label>LegalEntity  Accept Header</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityAuthorizationHeader__c</fullName>
        <description>Authorization header for legal entity requests</description>
        <inlineHelpText>Authorization header for legal entity requests</inlineHelpText>
        <label>LegalEntity  Authorization Header</label>
        <length>100</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>legalEntityContentTypeHeader__c</fullName>
        <description>Content type header for legal entity request</description>
        <inlineHelpText>Content type header for legal entity request</inlineHelpText>
        <label>LegalEntity  Content Type Header</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityEndpoint__c</fullName>
        <description>Endpoint for legal entity requests</description>
        <inlineHelpText>Endpoint for legal entity requests</inlineHelpText>
        <label>LegalEntity  Endpoint</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectName__c</fullName>
        <description>The name of the sObject of the logged request.</description>
        <inlineHelpText>The name of the sObject of the logged request.</inlineHelpText>
        <label>sObject Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>sObjectType__c</fullName>
        <description>Type Of Object (Account/Opportunity) which is logged.</description>
        <inlineHelpText>Type Of Object (Account/Opportunity) which is logged.</inlineHelpText>
        <label>sObject Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantAcceptHeader__c</fullName>
        <description>Accept Header of sub merchant request</description>
        <inlineHelpText>Accept Header of sub merchant request</inlineHelpText>
        <label>SubMerchant Accept Header</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantAuthorizationHeader__c</fullName>
        <description>Authorization header for sub merchant requests</description>
        <inlineHelpText>Authorization header for sub merchant requests</inlineHelpText>
        <label>Sub Merchant Authorization Header</label>
        <length>100</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>subMerchantContentTypeHeader__c</fullName>
        <description>Content Type Header of sub merchant request</description>
        <inlineHelpText>Content Type Header of sub merchant request</inlineHelpText>
        <label>SubMerchant Content Type Header</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantEndpoint__c</fullName>
        <description>Endpoint for create submerchant request</description>
        <inlineHelpText>Endpoint for create submerchant request</inlineHelpText>
        <label>SubMerchant Endpoint</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Litle Request Response Log</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>LogId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Request Response Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/classes/LogginUtilTest.cls
@isTest
private class LogginUtilTest {
	public static final String DEFAULT_NAME = 'test';
	public static final Date DEFAULT_DATE = Date.today();
	
	static testMethod void testlogSObjectDetailsAccount(){
		LitleRequestResponseLog__c litleRequestResponseLog = new LitleRequestResponseLog__c();
		// test for account
		Account account = new Account(name = DEFAULT_NAME);
		insert account;
		LoggingUtil.logSObjectDetails(account.id, null, litleRequestResponseLog);
		System.assertEquals('Account', litleRequestResponseLog.sObjectType__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.sObjectName__c);
		System.assertEquals(account.id, litleRequestResponseLog.Account__c);	
		System.assertEquals(null, litleRequestResponseLog.Opportunity__c);
		
		//test with bad account id
		litleRequestResponseLog = new LitleRequestResponseLog__c();
		LoggingUtil.logSObjectDetails('123', null, litleRequestResponseLog);
		System.assertEquals(null, litleRequestResponseLog.sObjectType__c);
		System.assertEquals(null, litleRequestResponseLog.sObjectName__c);
		System.assertEquals(null, litleRequestResponseLog.Account__c);	
		System.assertEquals(null, litleRequestResponseLog.Opportunity__c);	
		
		//test for opportunity
		Opportunity opportunity = new Opportunity(name = DEFAULT_NAME, stageName=DEFAULT_NAME, CloseDate=DEFAULT_DATE);
		insert opportunity;
		LoggingUtil.logSObjectDetails( null,opportunity.id, litleRequestResponseLog);
		System.assertEquals('Opportunity', litleRequestResponseLog.sObjectType__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.sObjectName__c);
		System.assertEquals(null, litleRequestResponseLog.Account__c);	
		System.assertEquals(opportunity.id, litleRequestResponseLog.Opportunity__c);	
		
		//test with bad opportunity id
		litleRequestResponseLog = new LitleRequestResponseLog__c();
		LoggingUtil.logSObjectDetails(null, '123', litleRequestResponseLog);
		System.assertEquals(null, litleRequestResponseLog.sObjectType__c);
		System.assertEquals(null, litleRequestResponseLog.sObjectName__c);
		System.assertEquals(null, litleRequestResponseLog.Account__c);	
		System.assertEquals(null, litleRequestResponseLog.Opportunity__c);
			
	} 
	static testMethod void testfillSObjectLogObject(){
		LitleRequestResponseLog__c litleRequestResponseLog = new LitleRequestResponseLog__c();
		LoggingUtil.fillSObjectLogObject(null, null, null, litleRequestResponseLog);
		System.assertEquals(null, litleRequestResponseLog.sObjectType__c);
		System.assertEquals(null, litleRequestResponseLog.sObjectName__c);
		System.assertEquals(null, litleRequestResponseLog.Account__c);
		System.assertEquals(null, litleRequestResponseLog.Opportunity__c);
	} 
	
	static testMethod void testFillSObject_Account(){
		LitleRequestResponseLog__c litleRequestResponseLog = new LitleRequestResponseLog__c();
		Account account = new Account(name = DEFAULT_NAME);
		insert account;
		LoggingUtil.fillSObjectLogObject('Account', DEFAULT_NAME, account.Id, litleRequestResponseLog);
		System.assertEquals('Account', litleRequestResponseLog.sObjectType__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.sObjectName__c);
		System.assertEquals(account.Id, litleRequestResponseLog.Account__c);
		System.assertEquals(null, litleRequestResponseLog.Opportunity__c);
	}
	
	static testMethod void testFillSObject_Opportunity(){
		LitleRequestResponseLog__c litleRequestResponseLog = new LitleRequestResponseLog__c();
		Opportunity opportunity = new Opportunity(name = DEFAULT_NAME, stageName=DEFAULT_NAME, CloseDate=DEFAULT_DATE);
		insert opportunity;
		LoggingUtil.fillSObjectLogObject('Opportunity', DEFAULT_NAME, opportunity.Id, litleRequestResponseLog);
		System.assertEquals('Opportunity', litleRequestResponseLog.sObjectType__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.sObjectName__c);
		System.assertEquals(null, litleRequestResponseLog.Account__c);
		System.assertEquals(opportunity.Id, litleRequestResponseLog.Opportunity__c);
	}
	
	static testMethod void testlogCreateLegalEntityRequest(){
		LitleRequestResponseLog__c litleRequestResponseLog = new LitleRequestResponseLog__c();
		// test null http request
		LoggingUtil.logCreateLegalEntityRequest(null, litleRequestResponseLog);
		System.assertEquals(null, litleRequestResponseLog.createLegalEntityRequestDate__c);
		System.assertEquals(null, litleRequestResponseLog.createLegalEntityRequestXml__c);
		System.assertEquals(null, litleRequestResponseLog.legalEntityEndpoint__c);
		System.assertEquals(null, litleRequestResponseLog.legalEntityAcceptHeader__c);
		System.assertEquals(null, litleRequestResponseLog.legalEntityContentTypeHeader__c);
		System.assertEquals(null, litleRequestResponseLog.legalEntityAuthorizationHeader__c);
		
		// test with http request
		litleRequestResponseLog = new LitleRequestResponseLog__c();
		HttpRequest request = new HttpRequest();
		request.setEndpoint(DEFAULT_NAME);
        request.setHeader(LitleConstants.REQUEST_HEADER_AUTHORIZATION, DEFAULT_NAME);
        request.setHeader(LitleConstants.REQUEST_HEADER_CONTENT_TYPE, DEFAULT_NAME);
		request.setHeader(LitleConstants.REQUEST_HEADER_ACCEPT, DEFAULT_NAME);
		request.setBody(DEFAULT_NAME);
		LoggingUtil.logCreateLegalEntityRequest(request, litleRequestResponseLog);
		System.assertNotEquals(null, litleRequestResponseLog.createLegalEntityRequestDate__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.createLegalEntityRequestXml__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.legalEntityEndpoint__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.legalEntityAcceptHeader__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.legalEntityContentTypeHeader__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.legalEntityAuthorizationHeader__c);
	} 
	static testMethod void testlogCreateSubMerchantRequest(){
		LitleRequestResponseLog__c litleRequestResponseLog = new LitleRequestResponseLog__c();
		// test null http request
		LoggingUtil.logCreateSubMerchantRequest(null, litleRequestResponseLog);
		System.assertEquals(null, litleRequestResponseLog.createSubMerchantRequestDate__c);
		System.assertEquals(null, litleRequestResponseLog.createSubMerchantRequestXml__c);
		System.assertEquals(null, litleRequestResponseLog.subMerchantEndpoint__c);
		System.assertEquals(null, litleRequestResponseLog.subMerchantAcceptHeader__c);
		System.assertEquals(null, litleRequestResponseLog.subMerchantContentTypeHeader__c);
		System.assertEquals(null, litleRequestResponseLog.subMerchantAuthorizationHeader__c);
		
		// test with http request
		litleRequestResponseLog = new LitleRequestResponseLog__c();
		HttpRequest request = new HttpRequest();
		request.setEndpoint(DEFAULT_NAME);
        request.setHeader(LitleConstants.REQUEST_HEADER_AUTHORIZATION, DEFAULT_NAME);
        request.setHeader(LitleConstants.REQUEST_HEADER_CONTENT_TYPE, DEFAULT_NAME);
		request.setHeader(LitleConstants.REQUEST_HEADER_ACCEPT, DEFAULT_NAME);
		request.setBody(DEFAULT_NAME);
		LoggingUtil.logCreateSubMerchantRequest(request, litleRequestResponseLog);
		System.assertNotEquals(null, litleRequestResponseLog.createSubMerchantRequestDate__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.createSubMerchantRequestXml__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.subMerchantEndpoint__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.subMerchantAcceptHeader__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.subMerchantContentTypeHeader__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.subMerchantAuthorizationHeader__c);	
	} 
	static testMethod void testLogCreateLegalEntityResponse(){
		LitleRequestResponseLog__c litleRequestResponseLog = new LitleRequestResponseLog__c();	
		HttpResponse response = new HttpResponse();	
		// test with blank response
		LoggingUtil.logCreateLegalEntityResponse(response, litleRequestResponseLog);
		System.assertNotEquals(null, litleRequestResponseLog.createLegalEntityResponseDate__c);
		System.assertEquals('', litleRequestResponseLog.createLegalEntityResponseXml__c);
		System.assertEquals('0', litleRequestResponseLog.createLegalEntityResponseStatusCode__c);	
		System.assertEquals(null, litleRequestResponseLog.createLegalEntityResponseStatusMessage__c);		
		
		// set response parameters
		response.setStatus(DEFAULT_NAME);
		response.setStatusCode(200);
		response.setBody(DEFAULT_NAME);
		LoggingUtil.logCreateLegalEntityResponse(response, litleRequestResponseLog);
		System.assertNotEquals(null, litleRequestResponseLog.createLegalEntityResponseDate__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.createLegalEntityResponseXml__c);
		System.assertEquals('200', litleRequestResponseLog.createLegalEntityResponseStatusCode__c);	
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.createLegalEntityResponseStatusMessage__c);	
	} 
	static testMethod void testLogCreateSubMerchantResponse(){
		LitleRequestResponseLog__c litleRequestResponseLog = new LitleRequestResponseLog__c();	
		HttpResponse response = new HttpResponse();	
		// test with blank response
		LoggingUtil.logCreateSubMerchantResponse(response, litleRequestResponseLog);
		System.assertNotEquals(null, litleRequestResponseLog.createSubMerchantResponseDate__c);
		System.assertEquals('', litleRequestResponseLog.createSubMerchantResponseXml__c);
		System.assertEquals('0', litleRequestResponseLog.createSubMerchantResponseStatusCode__c);	
		System.assertEquals(null, litleRequestResponseLog.createSubMerchantResponseStatusMessage__c);		
		
		// set response parameters
		response.setStatus(DEFAULT_NAME);
		response.setStatusCode(200);
		response.setBody(DEFAULT_NAME);
		LoggingUtil.logCreateSubMerchantResponse(response, litleRequestResponseLog);
		System.assertNotEquals(null, litleRequestResponseLog.createSubMerchantResponseDate__c);
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.createSubMerchantResponseXml__c);
		System.assertEquals('200', litleRequestResponseLog.createSubMerchantResponseStatusCode__c);	
		System.assertEquals(DEFAULT_NAME, litleRequestResponseLog.createSubMerchantResponseStatusMessage__c);	
	} 
	static testMethod void testGetRequestParamsLog(){
		System.assertEquals(null, LoggingUtil.getRequestParamsLog(null));
		HttpRequest request = new HttpRequest();
		// test with blank request
		System.assertEquals('Authorization: null\nContent-Type: null\nAccept: null\n', LoggingUtil.getRequestParamsLog(request));
		// set headers and body
		request.setHeader(LitleConstants.REQUEST_HEADER_AUTHORIZATION, DEFAULT_NAME);
		request.setHeader(LitleConstants.REQUEST_HEADER_CONTENT_TYPE, DEFAULT_NAME);
		request.setHeader(LitleConstants.REQUEST_HEADER_ACCEPT, DEFAULT_NAME);
		request.setBody(DEFAULT_NAME);
		System.assertEquals('Authorization: '+ DEFAULT_NAME +'\nContent-Type: '+ DEFAULT_NAME +'\nAccept: '+ DEFAULT_NAME +'\n'+ DEFAULT_NAME, LoggingUtil.getRequestParamsLog(request));
			
	} 
	static testMethod void testGetResponseParamsLog(){
		System.assertEquals(null, LoggingUtil.getResponseParamsLog(null));
		HttpResponse response = new HttpResponse();	
		System.assertEquals('', LoggingUtil.getResponseParamsLog(response));
		// set headers and body
		response.setHeader(LitleConstants.REQUEST_HEADER_AUTHORIZATION, DEFAULT_NAME);
		response.setHeader(LitleConstants.REQUEST_HEADER_CONTENT_TYPE, DEFAULT_NAME);
		response.setHeader(LitleConstants.REQUEST_HEADER_ACCEPT, DEFAULT_NAME);
		response.setBody(DEFAULT_NAME);
		System.assertEquals('Authorization :'+ DEFAULT_NAME  +'\nAccept :'+ DEFAULT_NAME +'\nContent-Type :'+ DEFAULT_NAME +'\n'+ DEFAULT_NAME, LoggingUtil.getResponseParamsLog(response));
		
	} 

}