salesforce-litle-MP/src/objects/Litle_Business__c.object
<CustomObject>
    <fields>
        <fullName>Litle_KYC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Litle KYC</label>
        <referenceTo>Litle_KYC__c</referenceTo>
        <relationshipLabel>Litle Business</relationshipLabel>
        <relationshipName>Litle_Business</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Litle Business</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle Business Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/Litle_KYC__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Litle KYC</relationshipLabel>
        <relationshipName>Litle_KYC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Litle KYC</relationshipLabel>
        <relationshipName>Litle_KYC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Litle KYC</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle KYC Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle KYC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/Litle_Principal__c.object
<CustomObject>
    <description>Stores the principal details of the KYC information</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First Name of the Principal</description>
        <inlineHelpText>First Name of the Principal</inlineHelpText>
        <label>First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last Name of the Principal</description>
        <inlineHelpText>Last Name of the Principal</inlineHelpText>
        <label>Last Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Litle_KYC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent KYC of the Principal</description>
        <inlineHelpText>Parent KYC of the Principal</inlineHelpText>
        <label>Litle KYC</label>
        <referenceTo>Litle_KYC__c</referenceTo>
        <relationshipLabel>Litle Principals</relationshipLabel>
        <relationshipName>Litle_Principals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Principal_Id__c</fullName>
        <description>Principal Id of the Principal</description>
        <inlineHelpText>Principal Id of the Principal</inlineHelpText>
        <label>Principal Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Litle Principal</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle Principal Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Principals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/Litle_Risk_Indicator__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Litle_Verification_Result__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Litle Verification Result</label>
        <referenceTo>Litle_Verification_Result__c</referenceTo>
        <relationshipLabel>Litle Risk Indicators</relationshipLabel>
        <relationshipName>Litle_Risk_Indicators</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Litle Risk Indicator</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle Risk Indicator Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Risk Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/Litle_Verification_Result__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Litle Verification Result</relationshipLabel>
        <relationshipName>Litle_Verification_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Verified__c</fullName>
        <label>Address Verified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_Verified__c</fullName>
        <label>City Verified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Litle_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Litle Business</label>
        <referenceTo>Litle_Business__c</referenceTo>
        <relationshipLabel>Litle Verification Result</relationshipLabel>
        <relationshipName>Litle_Verification_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Litle_Principal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Litle Principal</label>
        <referenceTo>Litle_Principal__c</referenceTo>
        <relationshipLabel>Litle Verification Result</relationshipLabel>
        <relationshipName>Litle_Verification_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_Address_Phone_Association_Code__c</fullName>
        <label>Name Address Phone Association Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Address_Phone_Association_Desc__c</fullName>
        <label>Name Address Phone Association Desc</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Address_TaxId_Association_Code__c</fullName>
        <label>Name Address TaxId Association Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Address_TaxId_Association_Desc__c</fullName>
        <label>Name Address TaxId Association Desc</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Verified__c</fullName>
        <label>Name Verified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Description__c</fullName>
        <label>Overall Description</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Score__c</fullName>
        <label>Overall Score</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Verified__c</fullName>
        <label>Phone Verified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaxId_Verified__c</fullName>
        <label>Tax Id Verified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Verified__c</fullName>
        <label>Zip Verified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Litle Verification Result</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle Verification Result Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Verification Result</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/classes/LitleKYCController.cls
public class LitleKYCController {
	
	public String urlAccountId {get; set;}
	public String urlOpportunityId {get; set;}
	public Account account {get; set;}
	public Opportunity opportunity {get; set;}
	public Litle_KYC__c litleKYC{get; set;}
	public Litle_Principal__c litlePrincipal{get; set;}
	public Litle_Business__c litleBusiness{get; set;}
	public Litle_Verification_Result__c litleBusinessVerificationResult{get; set;}
	public Litle_Verification_Result__c litlePrincipalVerificationResult{get; set;}
	public List<Litle_Risk_Indicator__c> litlePrincipalRiskIndicators{get; set;}
	public List<Litle_Risk_Indicator__c> litleBusinessRiskIndicators{get; set;}
	
	public LitleKYCController(){
		this.urlAccountId = apexpages.currentpage().getParameters().get('accid');
        this.urlOpportunityId =  apexpages.currentpage().getParameters().get('oppid');
        populateAccountOrOpportunity();
        populateLitleKYC();
        populateLitlePrincipal();
        populateLitleBusiness();
        populateLitleVerificationResult();
        populateRiskIndicators();
	}
	
	private void populateAccountOrOpportunity(){
		if(String.isNotEmpty(urlAccountId)){
        	try{
        		account = [select id, name from Account where id= :urlAccountId];
        	}catch(QueryException e){
        		System.debug('Error fetching account for id:' + urlAccountId + ' '+ e.getMessage());
        	}
        }else if(String.isNotEmpty(urlOpportunityId)){
        	try{
        		opportunity = [select id, name from Opportunity where id= :urlOpportunityId];
        	}catch(QueryException e){
        		System.debug('Error fetching opportunity for id:' + urlOpportunityId + ' '+ e.getMessage());
        	}
        }
	}
	
	private void populateLitleKYC(){
		if(account != null){
			try{
				litleKYC = [select id, name from Litle_KYC__c where Account__c = :account.Id];
			}catch(QueryException e){
        		System.debug('Error fetching Litle KYC for account id:' + account.Id + ' '+ e.getMessage());
        	}
		}else if(opportunity != null){
			try{
				litleKYC = [select id, name from Litle_KYC__c where Opportunity__c = :opportunity.Id];
			}catch(QueryException e){
        		System.debug('Error fetching Litle KYC for opportunity id:' + opportunity.Id + ' '+ e.getMessage());
        	}
		}
	}
	
	private void populateLitlePrincipal(){
		if(litleKYC != null){
			try{
				litlePrincipal = [select First_Name__c, Last_Name__c, Principal_Id__c from Litle_Principal__c where Litle_KYC__c = :litleKYC.Id];
			}catch(QueryException e){
        		System.debug('Error fetching Litle Principal for kyc id:' + litleKYC.Id + ' '+ e.getMessage());
        	}
		}
	}
	
	private void populateLitleBusiness(){
		if(litleKYC != null){
			try{
				litleBusiness = [select id, name from Litle_Business__c where Litle_KYC__c = :litleKYC.Id];
			}catch(QueryException e){
        		System.debug('Error fetching Litle Business for kyc id:' + litleKYC.Id + ' '+ e.getMessage());
        	}
		}
	}
	
	private void populateLitleVerificationResult(){
		if(litlePrincipal != null){
			try{
				litlePrincipalVerificationResult = 
				[select Address_Verified__c,
						City_Verified__c,
						Litle_Business__c,
						Litle_Principal__c,
						Name_Address_Phone_Association_Code__c,
						Name_Address_Phone_Association_Desc__c,
						Name_Address_TaxId_Association_Code__c,
						Name_Address_TaxId_Association_Desc__c,
						Name_Verified__c,
						Overall_Description__c,
						Overall_Score__c,
						Phone_Verified__c,
						TaxId_Verified__c,
						Zip_Verified__c 
					from Litle_Verification_Result__c 
					where Litle_Principal__c =:litlePrincipal.Id];
			}catch(QueryException e){
        		System.debug('Error fetching Verification result for Principal for litlePrincipal id:' + litlePrincipal.Id + ' '+ e.getMessage());
        	}
		}
		
		if(litleBusiness != null){
			try{
				litleBusinessVerificationResult 
				= [select Address_Verified__c,
						City_Verified__c,
						Litle_Business__c,
						Litle_Principal__c,
						Name_Address_Phone_Association_Code__c,
						Name_Address_Phone_Association_Desc__c,
						Name_Address_TaxId_Association_Code__c,
						Name_Address_TaxId_Association_Desc__c,
						Name_Verified__c,
						Overall_Description__c,
						Overall_Score__c,
						Phone_Verified__c,
						TaxId_Verified__c,
						Zip_Verified__c 
					from Litle_Verification_Result__c 
					where Litle_Business__c =:litleBusiness.Id];
			}catch(QueryException e){
        		System.debug('Error fetching Verification result for Business for litleBusiness id:' + litleBusiness.Id + ' '+ e.getMessage());
        	}
		}
	}
	
	private void populateRiskIndicators(){
		if(litlePrincipalVerificationResult != null){
			try{
				litlePrincipalRiskIndicators = 
				[select Code__c, 
						Description__c 
					from Litle_Risk_Indicator__c 
					where Litle_Verification_Result__c =:litlePrincipalVerificationResult.Id];
			}catch(QueryException e){
        		System.debug('Error fetching Risk Indicators for Principal for litlePrincipalVerificationResult id:' + 
        														litlePrincipalVerificationResult.Id + ' '+ e.getMessage());
        	}
		}
		
		if(litleBusinessVerificationResult != null){
			try{
				litleBusinessRiskIndicators = 
				[select Code__c, 
						Description__c 
					from Litle_Risk_Indicator__c 
					where Litle_Verification_Result__c =:litleBusinessVerificationResult.Id];
			}catch(QueryException e){
        		System.debug('Error fetching Risk Indicators for Business for litleBusinessVerificationResult id:' + 
        														litleBusinessVerificationResult.Id + ' '+ e.getMessage());
        	}
		}
	}
	
	public Pagereference cancel(){
	 	if(String.isNotEmpty(urlOpportunityId)){
	 		return new PageReference('/'+urlOpportunityId);
	 	}else if(String.isNotEmpty(urlAccountId)){
	 		return new PageReference('/'+urlAccountId);
	 	}
	 	return null;
	}

}