salesforce-litle-MP/src/objects/Litle_Business__c.object
<CustomObject>
    <fields>
        <fullName>Litle_KYC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Litle KYC</label>
        <referenceTo>Litle_KYC__c</referenceTo>
        <relationshipLabel>Litle Business</relationshipLabel>
        <relationshipName>Litle_Business</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Litle Business</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle Business Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Business</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/Litle_KYC__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Litle KYC</relationshipLabel>
        <relationshipName>Litle_KYC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Litle KYC</relationshipLabel>
        <relationshipName>Litle_KYC</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Litle KYC</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle KYC Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle KYC</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/Litle_Principal__c.object
<CustomObject>
    <description>Stores the principal details of the KYC information</description>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>First Name of the Principal</description>
        <inlineHelpText>First Name of the Principal</inlineHelpText>
        <label>First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Last Name of the Principal</description>
        <inlineHelpText>Last Name of the Principal</inlineHelpText>
        <label>Last Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Litle_KYC__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Parent KYC of the Principal</description>
        <inlineHelpText>Parent KYC of the Principal</inlineHelpText>
        <label>Litle KYC</label>
        <referenceTo>Litle_KYC__c</referenceTo>
        <relationshipLabel>Litle Principals</relationshipLabel>
        <relationshipName>Litle_Principals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Principal_Id__c</fullName>
        <description>Principal Id of the Principal</description>
        <inlineHelpText>Principal Id of the Principal</inlineHelpText>
        <label>Principal Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Litle Principal</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle Principal Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Principals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/Litle_Risk_Indicator__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Litle_Verification_Result__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Litle Verification Result</label>
        <referenceTo>Litle_Verification_Result__c</referenceTo>
        <relationshipLabel>Litle Risk Indicators</relationshipLabel>
        <relationshipName>Litle_Risk_Indicators</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Litle Risk Indicator</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle Risk Indicator Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Risk Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/Litle_Verification_Result__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Litle Verification Result</relationshipLabel>
        <relationshipName>Litle_Verification_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address_Verified__c</fullName>
        <label>Address Verified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City_Verified__c</fullName>
        <label>City Verified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Litle_Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Litle Business</label>
        <referenceTo>Litle_Business__c</referenceTo>
        <relationshipLabel>Litle Verification Result</relationshipLabel>
        <relationshipName>Litle_Verification_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Litle_Principal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Litle Principal</label>
        <referenceTo>Litle_Principal__c</referenceTo>
        <relationshipLabel>Litle Verification Result</relationshipLabel>
        <relationshipName>Litle_Verification_Result</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_Address_Phone_Association_Code__c</fullName>
        <label>Name Address Phone Association Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Address_Phone_Association_Desc__c</fullName>
        <label>Name Address Phone Association Desc</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Address_TaxId_Association_Code__c</fullName>
        <label>Name Address TaxId Association Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Address_TaxId_Association_Desc__c</fullName>
        <label>Name Address TaxId Association Desc</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_Verified__c</fullName>
        <label>Name Verified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Description__c</fullName>
        <label>Overall Description</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_Score__c</fullName>
        <label>Overall Score</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Verified__c</fullName>
        <label>Phone Verified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TaxId_Verified__c</fullName>
        <label>Tax Id Verified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Verified__c</fullName>
        <label>Zip Verified</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Litle Verification Result</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Litle Verification Result Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Verification Result</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/LitleRequestResponseLog__c.object
<CustomObject>
    <description>Object to log all the requests and responses to Litle MP</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Origination Account of the log</description>
        <inlineHelpText>Origination Account of the log</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>LitleRequestResponseLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Log_Source__c</fullName>
        <description>Displays if the source of this log is from the get litle mid form or from the scheduler</description>
        <inlineHelpText>Displays if the source of this log is from the get litle mid form or from the scheduler</inlineHelpText>
        <label>Log Source</label>
        <picklist>
            <picklistValues>
                <fullName>Get Litle MID action</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mcc Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KYC Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity causing this log entry</description>
        <inlineHelpText>Opportunity causing this log entry</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>LitleRequestResponseLogs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>createLegalEntityResponseStatusCode__c</fullName>
        <description>Create Legal Entity Response Status Code</description>
        <inlineHelpText>Create Legal Entity Response Status Code</inlineHelpText>
        <label>Create LegalEntity  ResponseStatusCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>createLegalEntityResponseStatusMessage__c</fullName>
        <description>Create Legal Entity Response Status Message</description>
        <inlineHelpText>Create Legal Entity Response Status Message</inlineHelpText>
        <label>Create LegalEntity  ResponseStatusMsg</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>createLegalEntityResponseXml__c</fullName>
        <description>Create Legal Entity Response Xml</description>
        <inlineHelpText>Create Legal Entity Response Xml</inlineHelpText>
        <label>Create LegalEntity  ResponseXml</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Litle Request Response Log</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>LogId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Litle Request Response Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/objects/SalesforceLitleMappingsObject__c.object
<CustomObject>
    <description>Salesforce and Litle&apos;s field mappings object</description>
    <fields>
        <fullName>litleEnvironment__c</fullName>
        <description>Stores the environment for MP</description>
        <label>Litle Environment</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>merchantPassword__c</fullName>
        <description>password used to connect to make litle request</description>
        <label>merchantPassword</label>
        <length>100</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>merchantUsername__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Merchant username for Litle requests</description>
        <label>merchantUsername</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>SalesforceLitleMappingsObject</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesforceLitleMappingsObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/classes/LitleKYCServiceTest.cls
/*
Copyright (c) 2013 Litle & Co.
Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:
The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
*/
@isTest
private class LitleKYCServiceTest {

    public static final String ACCOUNT_NAME = 'Test Account';
    public static final String OPPORTUNITY_NAME = 'Test Opportunity';
    public static final String DEFAULT_STRING = 'ab';
    public static final Date DEFAULT_DATE = Date.today();

    static testMethod void testKYCSaveInAccount_NoPreviousRecords() {
        // TO DO: implement unit test
        Account account = new Account(name=ACCOUNT_NAME);
        insert account;
        List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c where Account__c =:account.Id];
        System.assertEquals(0, litleKYCs.size());
        LegalEntityResponse leResponse = mockLegalEntityResponse(DEFAULT_STRING, 2);
        
        LitleKYCService litleService = new LitleKYCService();
        litleService.saveOrUpdateAllKYCObjects(null, account.Id, leResponse);
        
        //check kyc
        litleKYCs = [select Id, Name from Litle_KYC__c where Account__c =:account.Id];
        System.assertEquals(1, litleKYCs.size());
        //check business
        List<Litle_Business__c> litleBusiness = [select Id, Name 
                                                from Litle_Business__c 
                                                where Litle_KYC__c =:litleKYCs.get(0).Id];
        System.assertEquals(1, litleBusiness.size());
        //check business verification
        List<Litle_Verification_Result__c> businessVResults = [select Address_Verified__c,
                                                            City_Verified__c,
                                                            Litle_Business__c,
                                                            Litle_Principal__c,
                                                            Name_Address_Phone_Association_Code__c,
                                                            Name_Address_Phone_Association_Desc__c,
                                                            Name_Address_TaxId_Association_Code__c,
                                                            Name_Address_TaxId_Association_Desc__c,
                                                            Name_Verified__c,
                                                            Overall_Description__c,
                                                            Overall_Score__c,
                                                            Phone_Verified__c,
                                                            TaxId_Verified__c,
                                                            Zip_Verified__c 
                                                            from Litle_Verification_Result__c 
                                                            where Litle_Business__c =:litleBusiness.get(0).Id];
        System.assertEquals(1, businessVResults.size());
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Address_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).City_Verified__c);
        System.assertEquals(null, businessVResults.get(0).Litle_Principal__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_Phone_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_Phone_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_TaxId_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_TaxId_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Overall_Description__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Overall_Score__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Phone_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).TaxId_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Zip_Verified__c);
        
        //check business risk indicators
        List<Litle_Risk_Indicator__c> businessRisks = [select Code__c, Description__c 
                                                        from Litle_Risk_Indicator__c 
                                                        where Litle_Verification_Result__c =:businessVResults.get(0).Id];
        System.assertEquals(2, businessRisks.size());   
        System.assertEquals(DEFAULT_STRING, businessRisks.get(0).Code__c);
        System.assertEquals(DEFAULT_STRING, businessRisks.get(0).Description__c);
        System.assertEquals(DEFAULT_STRING, businessRisks.get(1).Code__c);
        System.assertEquals(DEFAULT_STRING, businessRisks.get(1).Description__c);   
                                                
        List<Litle_Principal__c> litlePrincipal = [select First_Name__c, Last_Name__c, Principal_Id__c, Id, Name 
                                                  from Litle_Principal__c 
                                                  where Litle_KYC__c =:litleKYCs.get(0).Id];
        System.assertEquals(1, litlePrincipal.size());
        //check principal verification
        List<Litle_Verification_Result__c> principalVResults = [select Address_Verified__c,
                                                            City_Verified__c,
                                                            Litle_Business__c,
                                                            Litle_Principal__c,
                                                            Name_Address_Phone_Association_Code__c,
                                                            Name_Address_Phone_Association_Desc__c,
                                                            Name_Address_TaxId_Association_Code__c,
                                                            Name_Address_TaxId_Association_Desc__c,
                                                            Name_Verified__c,
                                                            Overall_Description__c,
                                                            Overall_Score__c,
                                                            Phone_Verified__c,
                                                            TaxId_Verified__c,
                                                            Zip_Verified__c 
                                                            from Litle_Verification_Result__c 
                                                            where Litle_Principal__c =:litlePrincipal.get(0).Id];
        System.assertEquals(1, principalVResults.size());
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Address_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).City_Verified__c);
        System.assertEquals(null, principalVResults.get(0).Litle_Business__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_Phone_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_Phone_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_TaxId_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_TaxId_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Overall_Description__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Overall_Score__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Phone_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).TaxId_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Zip_Verified__c);
        
        //check principal risk indicators
        List<Litle_Risk_Indicator__c> principalRisks = [select Code__c, Description__c 
                                                        from Litle_Risk_Indicator__c 
                                                        where Litle_Verification_Result__c =:principalVResults.get(0).Id];
        System.assertEquals(2, principalRisks.size());  
        System.assertEquals(DEFAULT_STRING, principalRisks.get(0).Code__c);
        System.assertEquals(DEFAULT_STRING, principalRisks.get(0).Description__c);
        System.assertEquals(DEFAULT_STRING, principalRisks.get(1).Code__c);
        System.assertEquals(DEFAULT_STRING, principalRisks.get(1).Description__c);
    }
    
    static testMethod void testKYCSaveInAccount_OnePreviousRecords() {
        //setup custom objects
        Account account = new Account(name=ACCOUNT_NAME);
        insert account;
        
        Litle_KYC__c litleKYC = new Litle_KYC__c();
        litleKYC.Account__c = account.Id;
        insert litleKYC;
        
        Litle_Business__c litleBusiness = new Litle_Business__c();
        litleBusiness.Litle_KYC__c = litleKYC.Id;
        insert litleBusiness;
        
        Litle_Verification_Result__c businessVerification = new Litle_Verification_Result__c();
        businessVerification.Address_Verified__c = 'test';
        businessVerification.City_Verified__c = 'test';
        businessVerification.Litle_Business__c = litleBusiness.Id;
        businessVerification.Name_Address_Phone_Association_Code__c = 'test';
        businessVerification.Name_Address_Phone_Association_Desc__c = 'test';
        businessVerification.Name_Address_TaxId_Association_Code__c = 'test';
        businessVerification.Name_Address_TaxId_Association_Desc__c = 'test';
        businessVerification.Name_Verified__c = 'test';
        businessVerification.Overall_Description__c = 'test';
        businessVerification.Overall_Score__c = '12';
        businessVerification.Phone_Verified__c = 'test';
        businessVerification.TaxId_Verified__c = 'test';
        businessVerification.Zip_Verified__c = 'test';
        insert businessVerification; 
        
        Litle_Risk_Indicator__c businessRisk = new Litle_Risk_Indicator__c();
        businessRisk.Code__c = 'test';
        businessRisk.Description__c = 'test';
        businessRisk.Litle_Verification_Result__c = businessVerification.Id;
        insert businessRisk;
        
        Litle_Principal__c litlePrincipal = new Litle_Principal__c();
        litlePrincipal.Litle_KYC__c = litleKYC.Id;
        litlePrincipal.Principal_Id__c = '10';
        litlePrincipal.First_Name__c = 'First Name';
        litlePrincipal.Last_Name__c = 'Last Name';
        insert litlePrincipal;
        
        Litle_Verification_Result__c principalVerification = new Litle_Verification_Result__c();
        principalVerification.Address_Verified__c = 'test';
        principalVerification.City_Verified__c = 'test';
        principalVerification.Litle_Principal__c = litlePrincipal.Id;
        principalVerification.Name_Address_Phone_Association_Code__c = 'test';
        principalVerification.Name_Address_Phone_Association_Desc__c = 'test';
        principalVerification.Name_Address_TaxId_Association_Code__c = 'test';
        principalVerification.Name_Address_TaxId_Association_Desc__c = 'test';
        principalVerification.Name_Verified__c = 'test';
        principalVerification.Overall_Description__c = 'test';
        principalVerification.Overall_Score__c = '12';
        principalVerification.Phone_Verified__c = 'test';
        principalVerification.TaxId_Verified__c = 'test';
        principalVerification.Zip_Verified__c = 'test';
        insert principalVerification; 
        
        Litle_Risk_Indicator__c principalRisk = new Litle_Risk_Indicator__c();
        principalRisk.Code__c = 'test';
        principalRisk.Description__c = 'test';
        principalRisk.Litle_Verification_Result__c = principalVerification.Id;
        insert principalRisk;
        
        
        List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c where Account__c =:account.Id];
        System.assertEquals(1, litleKYCs.size());
        LegalEntityResponse leResponse = mockLegalEntityResponse(DEFAULT_STRING, 2);
        
        LitleKYCService litleService = new LitleKYCService();
        litleService.saveOrUpdateAllKYCObjects(null, account.Id, leResponse);
        
        //check kyc
        litleKYCs = [select Id, Name from Litle_KYC__c where Account__c =:account.Id];
        System.assertEquals(1, litleKYCs.size());
        //check business
        List<Litle_Business__c> litleBusinesses = [select Id, Name 
                                                from Litle_Business__c 
                                                where Litle_KYC__c =:litleKYCs.get(0).Id];
        System.assertEquals(1, litleBusinesses.size());
        //check business verification
        List<Litle_Verification_Result__c> businessVResults = [select Address_Verified__c,
                                                            City_Verified__c,
                                                            Litle_Business__c,
                                                            Litle_Principal__c,
                                                            Name_Address_Phone_Association_Code__c,
                                                            Name_Address_Phone_Association_Desc__c,
                                                            Name_Address_TaxId_Association_Code__c,
                                                            Name_Address_TaxId_Association_Desc__c,
                                                            Name_Verified__c,
                                                            Overall_Description__c,
                                                            Overall_Score__c,
                                                            Phone_Verified__c,
                                                            TaxId_Verified__c,
                                                            Zip_Verified__c 
                                                            from Litle_Verification_Result__c 
                                                            where Litle_Business__c =:litleBusinesses.get(0).Id];
        System.assertEquals(1, businessVResults.size());
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Address_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).City_Verified__c);
        System.assertEquals(null, businessVResults.get(0).Litle_Principal__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_Phone_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_Phone_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_TaxId_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_TaxId_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Overall_Description__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Overall_Score__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Phone_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).TaxId_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Zip_Verified__c);
        
        //check business risk indicators
        List<Litle_Risk_Indicator__c> businessRisks = [select Code__c, Description__c 
                                                        from Litle_Risk_Indicator__c 
                                                        where Litle_Verification_Result__c =:businessVResults.get(0).Id];
        System.assertEquals(2, businessRisks.size());   
        System.assertEquals(DEFAULT_STRING, businessRisks.get(0).Code__c);
        System.assertEquals(DEFAULT_STRING, businessRisks.get(0).Description__c);
        System.assertEquals(DEFAULT_STRING, businessRisks.get(1).Code__c);
        System.assertEquals(DEFAULT_STRING, businessRisks.get(1).Description__c);   
                                                
        List<Litle_Principal__c> litlePrincipals = [select First_Name__c, Last_Name__c, Principal_Id__c, Id, Name 
                                                  from Litle_Principal__c 
                                                  where Litle_KYC__c =:litleKYCs.get(0).Id];
        System.assertEquals(1, litlePrincipals.size());
        //check principal verification
        List<Litle_Verification_Result__c> principalVResults = [select Address_Verified__c,
                                                            City_Verified__c,
                                                            Litle_Business__c,
                                                            Litle_Principal__c,
                                                            Name_Address_Phone_Association_Code__c,
                                                            Name_Address_Phone_Association_Desc__c,
                                                            Name_Address_TaxId_Association_Code__c,
                                                            Name_Address_TaxId_Association_Desc__c,
                                                            Name_Verified__c,
                                                            Overall_Description__c,
                                                            Overall_Score__c,
                                                            Phone_Verified__c,
                                                            TaxId_Verified__c,
                                                            Zip_Verified__c 
                                                            from Litle_Verification_Result__c 
                                                            where Litle_Principal__c =:litlePrincipals.get(0).Id];
        System.assertEquals(1, principalVResults.size());
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Address_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).City_Verified__c);
        System.assertEquals(null, principalVResults.get(0).Litle_Business__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_Phone_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_Phone_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_TaxId_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_TaxId_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Overall_Description__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Overall_Score__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Phone_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).TaxId_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Zip_Verified__c);
        
        //check principal risk indicators
        List<Litle_Risk_Indicator__c> principalRisks = [select Code__c, Description__c 
                                                        from Litle_Risk_Indicator__c 
                                                        where Litle_Verification_Result__c =:principalVResults.get(0).Id];
        System.assertEquals(2, principalRisks.size());  
        System.assertEquals(DEFAULT_STRING, principalRisks.get(0).Code__c);
        System.assertEquals(DEFAULT_STRING, principalRisks.get(0).Description__c);
        System.assertEquals(DEFAULT_STRING, principalRisks.get(1).Code__c);
        System.assertEquals(DEFAULT_STRING, principalRisks.get(1).Description__c);
    }
    
    static testMethod void testKYCSaveInAccount_BlankResponse(){
        Account account = new Account(name=ACCOUNT_NAME);
        insert account;
        List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c where Account__c =:account.Id];
        System.assertEquals(0, litleKYCs.size());
        LegalEntityResponse leResponse = new LegalEntityResponse();
        
        LitleKYCService litleService = new LitleKYCService();
        litleService.saveOrUpdateAllKYCObjects(null, account.Id, leResponse);
        
        //check kyc
        litleKYCs = [select Id, Name from Litle_KYC__c where Account__c =:account.Id];
        System.assertEquals(1, litleKYCs.size());
        //check business
        List<Litle_Business__c> litleBusiness = [select Id, Name 
                                                from Litle_Business__c 
                                                where Litle_KYC__c =:litleKYCs.get(0).Id];
        System.assertEquals(1, litleBusiness.size());
        //check business verification
        List<Litle_Verification_Result__c> businessVResults = [select Address_Verified__c,
                                                            City_Verified__c,
                                                            Litle_Business__c,
                                                            Litle_Principal__c,
                                                            Name_Address_Phone_Association_Code__c,
                                                            Name_Address_Phone_Association_Desc__c,
                                                            Name_Address_TaxId_Association_Code__c,
                                                            Name_Address_TaxId_Association_Desc__c,
                                                            Name_Verified__c,
                                                            Overall_Description__c,
                                                            Overall_Score__c,
                                                            Phone_Verified__c,
                                                            TaxId_Verified__c,
                                                            Zip_Verified__c 
                                                            from Litle_Verification_Result__c 
                                                            where Litle_Business__c =:litleBusiness.get(0).Id];
        System.assertEquals(1, businessVResults.size());
        System.assertEquals(null, businessVResults.get(0).Address_Verified__c);
        System.assertEquals(null, businessVResults.get(0).City_Verified__c);
        System.assertEquals(null, businessVResults.get(0).Litle_Principal__c);
        System.assertEquals(null, businessVResults.get(0).Name_Address_Phone_Association_Code__c);
        System.assertEquals(null, businessVResults.get(0).Name_Address_Phone_Association_Desc__c);
        System.assertEquals(null, businessVResults.get(0).Name_Address_TaxId_Association_Code__c);
        System.assertEquals(null, businessVResults.get(0).Name_Address_TaxId_Association_Desc__c);
        System.assertEquals(null, businessVResults.get(0).Name_Verified__c);
        System.assertEquals(null, businessVResults.get(0).Overall_Description__c);
        System.assertEquals(null, businessVResults.get(0).Overall_Score__c);
        System.assertEquals(null, businessVResults.get(0).Phone_Verified__c);
        System.assertEquals(null, businessVResults.get(0).TaxId_Verified__c);
        System.assertEquals(null, businessVResults.get(0).Zip_Verified__c);
        
        //check business risk indicators
        List<Litle_Risk_Indicator__c> businessRisks = [select Code__c, Description__c 
                                                        from Litle_Risk_Indicator__c 
                                                        where Litle_Verification_Result__c =:businessVResults.get(0).Id];
        System.assertEquals(0, businessRisks.size());   
                                                
        List<Litle_Principal__c> litlePrincipal = [select First_Name__c, Last_Name__c, Principal_Id__c, Id, Name 
                                                  from Litle_Principal__c 
                                                  where Litle_KYC__c =:litleKYCs.get(0).Id];
        System.assertEquals(1, litlePrincipal.size());
        //check principal verification
        List<Litle_Verification_Result__c> principalVResults = [select Address_Verified__c,
                                                            City_Verified__c,
                                                            Litle_Business__c,
                                                            Litle_Principal__c,
                                                            Name_Address_Phone_Association_Code__c,
                                                            Name_Address_Phone_Association_Desc__c,
                                                            Name_Address_TaxId_Association_Code__c,
                                                            Name_Address_TaxId_Association_Desc__c,
                                                            Name_Verified__c,
                                                            Overall_Description__c,
                                                            Overall_Score__c,
                                                            Phone_Verified__c,
                                                            TaxId_Verified__c,
                                                            Zip_Verified__c 
                                                            from Litle_Verification_Result__c 
                                                            where Litle_Principal__c =:litlePrincipal.get(0).Id];
        System.assertEquals(1, principalVResults.size());
        System.assertEquals(null, principalVResults.get(0).Address_Verified__c);
        System.assertEquals(null, principalVResults.get(0).City_Verified__c);
        System.assertEquals(null, principalVResults.get(0).Litle_Business__c);
        System.assertEquals(null, principalVResults.get(0).Name_Address_Phone_Association_Code__c);
        System.assertEquals(null, principalVResults.get(0).Name_Address_Phone_Association_Desc__c);
        System.assertEquals(null, principalVResults.get(0).Name_Address_TaxId_Association_Code__c);
        System.assertEquals(null, principalVResults.get(0).Name_Address_TaxId_Association_Desc__c);
        System.assertEquals(null, principalVResults.get(0).Name_Verified__c);
        System.assertEquals(null, principalVResults.get(0).Overall_Description__c);
        System.assertEquals(null, principalVResults.get(0).Overall_Score__c);
        System.assertEquals(null, principalVResults.get(0).Phone_Verified__c);
        System.assertEquals(null, principalVResults.get(0).TaxId_Verified__c);
        System.assertEquals(null, principalVResults.get(0).Zip_Verified__c);
        
        //check principal risk indicators
        List<Litle_Risk_Indicator__c> principalRisks = [select Code__c, Description__c 
                                                        from Litle_Risk_Indicator__c 
                                                        where Litle_Verification_Result__c =:principalVResults.get(0).Id];
        System.assertEquals(0, principalRisks.size());  
    }
    
    static testMethod void testKYCSaveInAccount_NullResponse(){
        Account account = new Account(name=ACCOUNT_NAME);
        insert account;
        List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c where Account__c =:account.Id];
        System.assertEquals(0, litleKYCs.size());
        LitleKYCService litleService = new LitleKYCService();
        litleService.saveOrUpdateAllKYCObjects(null, account.Id, null);
        
        //check kyc
        litleKYCs = [select Id, Name from Litle_KYC__c where Account__c =:account.Id];
        System.assertEquals(0, litleKYCs.size());
        
        litleService.saveOrUpdateAllKYCObjects(null, null, new LegalEntityResponse());
        
        //check kyc
        litleKYCs = [select Id, Name from Litle_KYC__c where Account__c =:account.Id];
        System.assertEquals(0, litleKYCs.size());
    }
    
    static testMethod void testKYCSaveInOpportunity_NoPreviousRecords() {
        // TO DO: implement unit test
        Opportunity opportunity = new Opportunity(name=OPPORTUNITY_NAME, stageName=DEFAULT_STRING, CloseDate=DEFAULT_DATE);
        insert opportunity;
        List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c where Opportunity__c =:opportunity.Id];
        System.assertEquals(0, litleKYCs.size());
        LegalEntityResponse leResponse = mockLegalEntityResponse(DEFAULT_STRING, 2);
        
        LitleKYCService litleService = new LitleKYCService();
        litleService.saveOrUpdateAllKYCObjects(opportunity.Id,null, leResponse);
        
        //check kyc
        litleKYCs = [select Id, Name from Litle_KYC__c where Opportunity__c =:opportunity.Id];
        System.assertEquals(1, litleKYCs.size());
        //check business
        List<Litle_Business__c> litleBusiness = [select Id, Name 
                                                from Litle_Business__c 
                                                where Litle_KYC__c =:litleKYCs.get(0).Id];
        System.assertEquals(1, litleBusiness.size());
        //check business verification
        List<Litle_Verification_Result__c> businessVResults = [select Address_Verified__c,
                                                            City_Verified__c,
                                                            Litle_Business__c,
                                                            Litle_Principal__c,
                                                            Name_Address_Phone_Association_Code__c,
                                                            Name_Address_Phone_Association_Desc__c,
                                                            Name_Address_TaxId_Association_Code__c,
                                                            Name_Address_TaxId_Association_Desc__c,
                                                            Name_Verified__c,
                                                            Overall_Description__c,
                                                            Overall_Score__c,
                                                            Phone_Verified__c,
                                                            TaxId_Verified__c,
                                                            Zip_Verified__c 
                                                            from Litle_Verification_Result__c 
                                                            where Litle_Business__c =:litleBusiness.get(0).Id];
        System.assertEquals(1, businessVResults.size());
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Address_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).City_Verified__c);
        System.assertEquals(null, businessVResults.get(0).Litle_Principal__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_Phone_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_Phone_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_TaxId_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_TaxId_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Overall_Description__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Overall_Score__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Phone_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).TaxId_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Zip_Verified__c);
        
        //check business risk indicators
        List<Litle_Risk_Indicator__c> businessRisks = [select Code__c, Description__c 
                                                        from Litle_Risk_Indicator__c 
                                                        where Litle_Verification_Result__c =:businessVResults.get(0).Id];
        System.assertEquals(2, businessRisks.size());   
        System.assertEquals(DEFAULT_STRING, businessRisks.get(0).Code__c);
        System.assertEquals(DEFAULT_STRING, businessRisks.get(0).Description__c);
        System.assertEquals(DEFAULT_STRING, businessRisks.get(1).Code__c);
        System.assertEquals(DEFAULT_STRING, businessRisks.get(1).Description__c);   
                                                
        List<Litle_Principal__c> litlePrincipal = [select First_Name__c, Last_Name__c, Principal_Id__c, Id, Name 
                                                  from Litle_Principal__c 
                                                  where Litle_KYC__c =:litleKYCs.get(0).Id];
        System.assertEquals(1, litlePrincipal.size());
        //check principal verification
        List<Litle_Verification_Result__c> principalVResults = [select Address_Verified__c,
                                                            City_Verified__c,
                                                            Litle_Business__c,
                                                            Litle_Principal__c,
                                                            Name_Address_Phone_Association_Code__c,
                                                            Name_Address_Phone_Association_Desc__c,
                                                            Name_Address_TaxId_Association_Code__c,
                                                            Name_Address_TaxId_Association_Desc__c,
                                                            Name_Verified__c,
                                                            Overall_Description__c,
                                                            Overall_Score__c,
                                                            Phone_Verified__c,
                                                            TaxId_Verified__c,
                                                            Zip_Verified__c 
                                                            from Litle_Verification_Result__c 
                                                            where Litle_Principal__c =:litlePrincipal.get(0).Id];
        System.assertEquals(1, principalVResults.size());
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Address_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).City_Verified__c);
        System.assertEquals(null, principalVResults.get(0).Litle_Business__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_Phone_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_Phone_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_TaxId_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_TaxId_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Overall_Description__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Overall_Score__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Phone_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).TaxId_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Zip_Verified__c);
        
        //check principal risk indicators
        List<Litle_Risk_Indicator__c> principalRisks = [select Code__c, Description__c 
                                                        from Litle_Risk_Indicator__c 
                                                        where Litle_Verification_Result__c =:principalVResults.get(0).Id];
        System.assertEquals(2, principalRisks.size());  
        System.assertEquals(DEFAULT_STRING, principalRisks.get(0).Code__c);
        System.assertEquals(DEFAULT_STRING, principalRisks.get(0).Description__c);
        System.assertEquals(DEFAULT_STRING, principalRisks.get(1).Code__c);
        System.assertEquals(DEFAULT_STRING, principalRisks.get(1).Description__c);
    }
    
    static testMethod void testKYCSaveInOpportunity_OnePreviousRecords() {
        //setup custom objects
        Opportunity opportunity = new Opportunity(name=OPPORTUNITY_NAME, stageName=DEFAULT_STRING, CloseDate=DEFAULT_DATE);
        insert opportunity;
        
        Litle_KYC__c litleKYC = new Litle_KYC__c();
        litleKYC.Opportunity__c = opportunity.Id;
        insert litleKYC;
        
        Litle_Business__c litleBusiness = new Litle_Business__c();
        litleBusiness.Litle_KYC__c = litleKYC.Id;
        insert litleBusiness;
        
        Litle_Verification_Result__c businessVerification = new Litle_Verification_Result__c();
        businessVerification.Address_Verified__c = 'test';
        businessVerification.City_Verified__c = 'test';
        businessVerification.Litle_Business__c = litleBusiness.Id;
        businessVerification.Name_Address_Phone_Association_Code__c = 'test';
        businessVerification.Name_Address_Phone_Association_Desc__c = 'test';
        businessVerification.Name_Address_TaxId_Association_Code__c = 'test';
        businessVerification.Name_Address_TaxId_Association_Desc__c = 'test';
        businessVerification.Name_Verified__c = 'test';
        businessVerification.Overall_Description__c = 'test';
        businessVerification.Overall_Score__c = '12';
        businessVerification.Phone_Verified__c = 'test';
        businessVerification.TaxId_Verified__c = 'test';
        businessVerification.Zip_Verified__c = 'test';
        insert businessVerification; 
        
        Litle_Risk_Indicator__c businessRisk = new Litle_Risk_Indicator__c();
        businessRisk.Code__c = 'test';
        businessRisk.Description__c = 'test';
        businessRisk.Litle_Verification_Result__c = businessVerification.Id;
        insert businessRisk;
        
        Litle_Principal__c litlePrincipal = new Litle_Principal__c();
        litlePrincipal.Litle_KYC__c = litleKYC.Id;
        litlePrincipal.Principal_Id__c = '10';
        litlePrincipal.First_Name__c = 'First Name';
        litlePrincipal.Last_Name__c = 'Last Name';
        insert litlePrincipal;
        
        Litle_Verification_Result__c principalVerification = new Litle_Verification_Result__c();
        principalVerification.Address_Verified__c = 'test';
        principalVerification.City_Verified__c = 'test';
        principalVerification.Litle_Principal__c = litlePrincipal.Id;
        principalVerification.Name_Address_Phone_Association_Code__c = 'test';
        principalVerification.Name_Address_Phone_Association_Desc__c = 'test';
        principalVerification.Name_Address_TaxId_Association_Code__c = 'test';
        principalVerification.Name_Address_TaxId_Association_Desc__c = 'test';
        principalVerification.Name_Verified__c = 'test';
        principalVerification.Overall_Description__c = 'test';
        principalVerification.Overall_Score__c = '12';
        principalVerification.Phone_Verified__c = 'test';
        principalVerification.TaxId_Verified__c = 'test';
        principalVerification.Zip_Verified__c = 'test';
        insert principalVerification; 
        
        Litle_Risk_Indicator__c principalRisk = new Litle_Risk_Indicator__c();
        principalRisk.Code__c = 'test';
        principalRisk.Description__c = 'test';
        principalRisk.Litle_Verification_Result__c = principalVerification.Id;
        insert principalRisk;
        
        
        List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c where Opportunity__c =:opportunity.Id];
        System.assertEquals(1, litleKYCs.size());
        LegalEntityResponse leResponse = mockLegalEntityResponse(DEFAULT_STRING, 2);
        
        LitleKYCService litleService = new LitleKYCService();
        litleService.saveOrUpdateAllKYCObjects(opportunity.Id,null, leResponse);
        
        //check kyc
        litleKYCs = [select Id, Name from Litle_KYC__c where Opportunity__c =:opportunity.Id];
        System.assertEquals(1, litleKYCs.size());
        //check business
        List<Litle_Business__c> litleBusinesses = [select Id, Name 
                                                from Litle_Business__c 
                                                where Litle_KYC__c =:litleKYCs.get(0).Id];
        System.assertEquals(1, litleBusinesses.size());
        //check business verification
        List<Litle_Verification_Result__c> businessVResults = [select Address_Verified__c,
                                                            City_Verified__c,
                                                            Litle_Business__c,
                                                            Litle_Principal__c,
                                                            Name_Address_Phone_Association_Code__c,
                                                            Name_Address_Phone_Association_Desc__c,
                                                            Name_Address_TaxId_Association_Code__c,
                                                            Name_Address_TaxId_Association_Desc__c,
                                                            Name_Verified__c,
                                                            Overall_Description__c,
                                                            Overall_Score__c,
                                                            Phone_Verified__c,
                                                            TaxId_Verified__c,
                                                            Zip_Verified__c 
                                                            from Litle_Verification_Result__c 
                                                            where Litle_Business__c =:litleBusinesses.get(0).Id];
        System.assertEquals(1, businessVResults.size());
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Address_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).City_Verified__c);
        System.assertEquals(null, businessVResults.get(0).Litle_Principal__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_Phone_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_Phone_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_TaxId_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Address_TaxId_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Name_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Overall_Description__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Overall_Score__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Phone_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).TaxId_Verified__c);
        System.assertEquals(DEFAULT_STRING, businessVResults.get(0).Zip_Verified__c);
        
        //check business risk indicators
        List<Litle_Risk_Indicator__c> businessRisks = [select Code__c, Description__c 
                                                        from Litle_Risk_Indicator__c 
                                                        where Litle_Verification_Result__c =:businessVResults.get(0).Id];
        System.assertEquals(2, businessRisks.size());   
        System.assertEquals(DEFAULT_STRING, businessRisks.get(0).Code__c);
        System.assertEquals(DEFAULT_STRING, businessRisks.get(0).Description__c);
        System.assertEquals(DEFAULT_STRING, businessRisks.get(1).Code__c);
        System.assertEquals(DEFAULT_STRING, businessRisks.get(1).Description__c);   
                                                
        List<Litle_Principal__c> litlePrincipals = [select First_Name__c, Last_Name__c, Principal_Id__c, Id, Name 
                                                  from Litle_Principal__c 
                                                  where Litle_KYC__c =:litleKYCs.get(0).Id];
        System.assertEquals(1, litlePrincipals.size());
        //check principal verification
        List<Litle_Verification_Result__c> principalVResults = [select Address_Verified__c,
                                                            City_Verified__c,
                                                            Litle_Business__c,
                                                            Litle_Principal__c,
                                                            Name_Address_Phone_Association_Code__c,
                                                            Name_Address_Phone_Association_Desc__c,
                                                            Name_Address_TaxId_Association_Code__c,
                                                            Name_Address_TaxId_Association_Desc__c,
                                                            Name_Verified__c,
                                                            Overall_Description__c,
                                                            Overall_Score__c,
                                                            Phone_Verified__c,
                                                            TaxId_Verified__c,
                                                            Zip_Verified__c 
                                                            from Litle_Verification_Result__c 
                                                            where Litle_Principal__c =:litlePrincipals.get(0).Id];
        System.assertEquals(1, principalVResults.size());
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Address_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).City_Verified__c);
        System.assertEquals(null, principalVResults.get(0).Litle_Business__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_Phone_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_Phone_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_TaxId_Association_Code__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Address_TaxId_Association_Desc__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Name_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Overall_Description__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Overall_Score__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Phone_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).TaxId_Verified__c);
        System.assertEquals(DEFAULT_STRING, principalVResults.get(0).Zip_Verified__c);
        
        //check principal risk indicators
        List<Litle_Risk_Indicator__c> principalRisks = [select Code__c, Description__c 
                                                        from Litle_Risk_Indicator__c 
                                                        where Litle_Verification_Result__c =:principalVResults.get(0).Id];
        System.assertEquals(2, principalRisks.size());  
        System.assertEquals(DEFAULT_STRING, principalRisks.get(0).Code__c);
        System.assertEquals(DEFAULT_STRING, principalRisks.get(0).Description__c);
        System.assertEquals(DEFAULT_STRING, principalRisks.get(1).Code__c);
        System.assertEquals(DEFAULT_STRING, principalRisks.get(1).Description__c);
    }
    
    static testMethod void testKYCSaveInOpportunity_BlankResponse(){
        Opportunity opportunity = new Opportunity(name=OPPORTUNITY_NAME, stageName=DEFAULT_STRING, CloseDate=DEFAULT_DATE);
        insert opportunity;
        List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c where Opportunity__c =:opportunity.Id];
        System.assertEquals(0, litleKYCs.size());
        LegalEntityResponse leResponse = new LegalEntityResponse();
        
        LitleKYCService litleService = new LitleKYCService();
        litleService.saveOrUpdateAllKYCObjects(opportunity.Id,null, leResponse);
        
        //check kyc
        litleKYCs = [select Id, Name from Litle_KYC__c where Opportunity__c =:opportunity.Id];
        System.assertEquals(1, litleKYCs.size());
        //check business
        List<Litle_Business__c> litleBusiness = [select Id, Name 
                                                from Litle_Business__c 
                                                where Litle_KYC__c =:litleKYCs.get(0).Id];
        System.assertEquals(1, litleBusiness.size());
        //check business verification
        List<Litle_Verification_Result__c> businessVResults = [select Address_Verified__c,
                                                            City_Verified__c,
                                                            Litle_Business__c,
                                                            Litle_Principal__c,
                                                            Name_Address_Phone_Association_Code__c,
                                                            Name_Address_Phone_Association_Desc__c,
                                                            Name_Address_TaxId_Association_Code__c,
                                                            Name_Address_TaxId_Association_Desc__c,
                                                            Name_Verified__c,
                                                            Overall_Description__c,
                                                            Overall_Score__c,
                                                            Phone_Verified__c,
                                                            TaxId_Verified__c,
                                                            Zip_Verified__c 
                                                            from Litle_Verification_Result__c 
                                                            where Litle_Business__c =:litleBusiness.get(0).Id];
        System.assertEquals(1, businessVResults.size());
        System.assertEquals(null, businessVResults.get(0).Address_Verified__c);
        System.assertEquals(null, businessVResults.get(0).City_Verified__c);
        System.assertEquals(null, businessVResults.get(0).Litle_Principal__c);
        System.assertEquals(null, businessVResults.get(0).Name_Address_Phone_Association_Code__c);
        System.assertEquals(null, businessVResults.get(0).Name_Address_Phone_Association_Desc__c);
        System.assertEquals(null, businessVResults.get(0).Name_Address_TaxId_Association_Code__c);
        System.assertEquals(null, businessVResults.get(0).Name_Address_TaxId_Association_Desc__c);
        System.assertEquals(null, businessVResults.get(0).Name_Verified__c);
        System.assertEquals(null, businessVResults.get(0).Overall_Description__c);
        System.assertEquals(null, businessVResults.get(0).Overall_Score__c);
        System.assertEquals(null, businessVResults.get(0).Phone_Verified__c);
        System.assertEquals(null, businessVResults.get(0).TaxId_Verified__c);
        System.assertEquals(null, businessVResults.get(0).Zip_Verified__c);
        
        //check business risk indicators
        List<Litle_Risk_Indicator__c> businessRisks = [select Code__c, Description__c 
                                                        from Litle_Risk_Indicator__c 
                                                        where Litle_Verification_Result__c =:businessVResults.get(0).Id];
        System.assertEquals(0, businessRisks.size());   
                                                
        List<Litle_Principal__c> litlePrincipal = [select First_Name__c, Last_Name__c, Principal_Id__c, Id, Name 
                                                  from Litle_Principal__c 
                                                  where Litle_KYC__c =:litleKYCs.get(0).Id];
        System.assertEquals(1, litlePrincipal.size());
        //check principal verification
        List<Litle_Verification_Result__c> principalVResults = [select Address_Verified__c,
                                                            City_Verified__c,
                                                            Litle_Business__c,
                                                            Litle_Principal__c,
                                                            Name_Address_Phone_Association_Code__c,
                                                            Name_Address_Phone_Association_Desc__c,
                                                            Name_Address_TaxId_Association_Code__c,
                                                            Name_Address_TaxId_Association_Desc__c,
                                                            Name_Verified__c,
                                                            Overall_Description__c,
                                                            Overall_Score__c,
                                                            Phone_Verified__c,
                                                            TaxId_Verified__c,
                                                            Zip_Verified__c 
                                                            from Litle_Verification_Result__c 
                                                            where Litle_Principal__c =:litlePrincipal.get(0).Id];
        System.assertEquals(1, principalVResults.size());
        System.assertEquals(null, principalVResults.get(0).Address_Verified__c);
        System.assertEquals(null, principalVResults.get(0).City_Verified__c);
        System.assertEquals(null, principalVResults.get(0).Litle_Business__c);
        System.assertEquals(null, principalVResults.get(0).Name_Address_Phone_Association_Code__c);
        System.assertEquals(null, principalVResults.get(0).Name_Address_Phone_Association_Desc__c);
        System.assertEquals(null, principalVResults.get(0).Name_Address_TaxId_Association_Code__c);
        System.assertEquals(null, principalVResults.get(0).Name_Address_TaxId_Association_Desc__c);
        System.assertEquals(null, principalVResults.get(0).Name_Verified__c);
        System.assertEquals(null, principalVResults.get(0).Overall_Description__c);
        System.assertEquals(null, principalVResults.get(0).Overall_Score__c);
        System.assertEquals(null, principalVResults.get(0).Phone_Verified__c);
        System.assertEquals(null, principalVResults.get(0).TaxId_Verified__c);
        System.assertEquals(null, principalVResults.get(0).Zip_Verified__c);
        
        //check principal risk indicators
        List<Litle_Risk_Indicator__c> principalRisks = [select Code__c, Description__c 
                                                        from Litle_Risk_Indicator__c 
                                                        where Litle_Verification_Result__c =:principalVResults.get(0).Id];
        System.assertEquals(0, principalRisks.size());  
    }
    
    static testMethod void testKYCSaveInOpportunity_NullResponse(){
        Opportunity opportunity = new Opportunity(name=OPPORTUNITY_NAME, stageName=DEFAULT_STRING, CloseDate=DEFAULT_DATE);
        insert opportunity;
        List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c where Opportunity__c =:opportunity.Id];
        System.assertEquals(0, litleKYCs.size());
        LitleKYCService litleService = new LitleKYCService();
        litleService.saveOrUpdateAllKYCObjects(opportunity.Id,null, null);
        
        //check kyc
        litleKYCs = [select Id, Name from Litle_KYC__c where Opportunity__c =:opportunity.Id];
        System.assertEquals(0, litleKYCs.size());
        
        litleService.saveOrUpdateAllKYCObjects(null, null, new LegalEntityResponse());
        
        //check kyc
        litleKYCs = [select Id, Name from Litle_KYC__c where Opportunity__c =:opportunity.Id];
        System.assertEquals(0, litleKYCs.size());
    }
    
    static LegalEntityResponse mockLegalEntityResponse(String defaultValue, Integer risks){
        LegalEntityResponse lr = new LegalEntityResponse();
        lr.getResponsePrincipal().setPrincipalId(defaultValue);
        lr.getResponsePrincipal().setFirstName(defaultValue);
        lr.getResponsePrincipal().setLastName(defaultValue);
        lr.getBusinessVerificationResult().getOverallScore().setCodeOrScore(defaultValue);
        lr.getBusinessVerificationResult().getOverallScore().setDescription(defaultValue);
        lr.getBusinessVerificationResult().getNameAddressTaxOrSsnIdAssociation().setCodeOrScore(defaultValue);
        lr.getBusinessVerificationResult().getNameAddressTaxOrSsnIdAssociation().setDescription(defaultValue);
        lr.getBusinessVerificationResult().getNameAddressPhoneAssociation().setCodeOrScore(defaultValue);
        lr.getBusinessVerificationResult().getNameAddressPhoneAssociation().setDescription(defaultValue);
        lr.getBusinessVerificationResult().getVerificationIndicator().setAddressVerified(defaultValue);
        lr.getBusinessVerificationResult().getVerificationIndicator().setCityVerified(defaultValue);
        lr.getBusinessVerificationResult().getVerificationIndicator().setNameVerified(defaultValue);
        lr.getBusinessVerificationResult().getVerificationIndicator().setTaxIdVerified(defaultValue);
        lr.getBusinessVerificationResult().getVerificationIndicator().setPhoneVerified(defaultValue);
        lr.getBusinessVerificationResult().getVerificationIndicator().setSsnVerified(defaultValue);
        lr.getBusinessVerificationResult().getVerificationIndicator().setDobVerified(defaultValue);
        lr.getBusinessVerificationResult().getVerificationIndicator().setZipVerified(defaultValue);
        Integer counter = risks;
        while(counter != 0){
            DescriptionDetails details = new DescriptionDetails();
            details.setCodeOrScore(defaultValue);
            details.setDescription(defaultValue);
            lr.getBusinessVerificationResult().getRiskIndicators().add(details);
            counter--;
        }
        
        lr.getPrincipalVerificationResult().getOverallScore().setCodeOrScore(defaultValue);
        lr.getPrincipalVerificationResult().getOverallScore().setDescription(defaultValue);
        lr.getPrincipalVerificationResult().getNameAddressTaxOrSsnIdAssociation().setCodeOrScore(defaultValue);
        lr.getPrincipalVerificationResult().getNameAddressTaxOrSsnIdAssociation().setDescription(defaultValue);
        lr.getPrincipalVerificationResult().getNameAddressPhoneAssociation().setCodeOrScore(defaultValue);
        lr.getPrincipalVerificationResult().getNameAddressPhoneAssociation().setDescription(defaultValue);
        lr.getPrincipalVerificationResult().getVerificationIndicator().setAddressVerified(defaultValue);
        lr.getPrincipalVerificationResult().getVerificationIndicator().setCityVerified(defaultValue);
        lr.getPrincipalVerificationResult().getVerificationIndicator().setNameVerified(defaultValue);
        lr.getPrincipalVerificationResult().getVerificationIndicator().setTaxIdVerified(defaultValue);
        lr.getPrincipalVerificationResult().getVerificationIndicator().setPhoneVerified(defaultValue);
        lr.getPrincipalVerificationResult().getVerificationIndicator().setSsnVerified(defaultValue);
        lr.getPrincipalVerificationResult().getVerificationIndicator().setDobVerified(defaultValue);
        lr.getPrincipalVerificationResult().getVerificationIndicator().setZipVerified(defaultValue);
        counter = risks;
        while(counter != 0){
            DescriptionDetails details = new DescriptionDetails();
            details.setCodeOrScore(defaultValue);
            details.setDescription(defaultValue);
            lr.getPrincipalVerificationResult().getRiskIndicators().add(details);
            counter--;
        }
        return lr;
    }
    
    static testMethod void fetchKycForAccountFromMP_NoAccount(){
    	LitleKYCService litleKYCService = new LitleKYCService();
    	List<litleRequestResponseLog__c> kyclog = [select Id, name from litleRequestResponseLog__c where Log_Source__c ='KYC Request'];
    	System.assertEquals(0, kyclog.size());
    	List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c];
        System.assertEquals(0, litleKYCs.size());
    	litleKYCService.fetchKycForAccountFromMP(null);
    	kyclog = [select Id, name from litleRequestResponseLog__c where Log_Source__c ='KYC Request'];
    	System.assertEquals(0, kyclog.size());
    	litleKYCs = [select Id, Name from Litle_KYC__c];
        System.assertEquals(0, litleKYCs.size());
    }
    
    static testMethod void fetchKycForAccountFromMP_NoLitleLegalEntity(){
    	LitleKYCService litleKYCService = new LitleKYCService();
 		Account account = new Account(name=ACCOUNT_NAME);
        insert account;
    	List<litleRequestResponseLog__c> kyclog = [select Id, name from litleRequestResponseLog__c where Log_Source__c ='KYC Request'];
    	System.assertEquals(0, kyclog.size());
    	List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c];
        System.assertEquals(0, litleKYCs.size());
    	litleKYCService.fetchKycForAccountFromMP(account);
    	kyclog = [select Id, name from litleRequestResponseLog__c where Log_Source__c ='KYC Request'];
    	System.assertEquals(0, kyclog.size());
    	litleKYCs = [select Id, Name from Litle_KYC__c];
        System.assertEquals(0, litleKYCs.size());
    }
    
    
    static testMethod void fetchKycForAccountFromMP_NoMapping(){
    	LitleKYCService litleKYCService = new LitleKYCService();
 		Account account = new Account(name=ACCOUNT_NAME, LitleLegalEntityId__c = 'testLitleLegalEntityId__c');
        insert account;
    	List<litleRequestResponseLog__c> kyclog = [select Id, name from litleRequestResponseLog__c where Log_Source__c ='KYC Request'];
    	System.assertEquals(0, kyclog.size());
    	List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c];
        System.assertEquals(0, litleKYCs.size());
        try{
     		litleKYCService.fetchKycForAccountFromMP(account);       	
        }catch(Exception e){
        	System.assertEquals('No Mapping record present.',e.getMessage());
        }
        kyclog = [select Id, name from litleRequestResponseLog__c where Log_Source__c ='KYC Request'];
    	System.assertEquals(0, kyclog.size());
    	litleKYCs = [select Id, Name from Litle_KYC__c];
        System.assertEquals(0, litleKYCs.size());
    }
    
    static testMethod void fetchKycForAccountFromMP_NoUsernameInMapping(){
    	LitleKYCService litleKYCService = new LitleKYCService();
 		Account account = new Account(name=ACCOUNT_NAME, LitleLegalEntityId__c = 'testLitleLegalEntityId__c');
        insert account;
        SalesforceLitleMappingsObject__c mappingObject = new SalesforceLitleMappingsObject__c();
        mappingObject.LitleEnvironment__c = 'CERT';
        insert mappingObject;
		List<litleRequestResponseLog__c> kyclog = [select Id, name from litleRequestResponseLog__c where Log_Source__c ='KYC Request'];
    	System.assertEquals(0, kyclog.size());
    	List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c];
        System.assertEquals(0, litleKYCs.size());        
        try{
     		litleKYCService.fetchKycForAccountFromMP(account);       	
        }catch(Exception e){
        	System.assertEquals('PayFac Username, Password and Litle Environment are required to get KYC Information. One or more value missing in mappings.',e.getMessage());
        }  
        kyclog = [select Id, name from litleRequestResponseLog__c where Log_Source__c ='KYC Request'];
    	System.assertEquals(0, kyclog.size());
    	litleKYCs = [select Id, Name from Litle_KYC__c];
        System.assertEquals(0, litleKYCs.size());          	
    }
    
    static testMethod void fetchKycForAccountFromMP_InvalidUsernameInMapping(){
    	LitleKYCService litleKYCService = new LitleKYCService();
 		Account account = new Account(name=ACCOUNT_NAME, LitleLegalEntityId__c = 'testLitleLegalEntityId__c');
        insert account;
        SalesforceLitleMappingsObject__c mappingObject = new SalesforceLitleMappingsObject__c();
        mappingObject.MerchantUsername__c = 'testUsername';
        mappingObject.MerchantPassword__c = 'testPassword';
        mappingObject.LitleEnvironment__c = 'CERT';
        insert mappingObject;
		List<litleRequestResponseLog__c> kyclog = [select Id, name from litleRequestResponseLog__c where Log_Source__c ='KYC Request'];
    	System.assertEquals(0, kyclog.size());
    	List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c];
        System.assertEquals(0, litleKYCs.size()); 
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(new LitleErrorResponse(), null));       
 		litleKYCService.fetchKycForAccountFromMP(account);       	
        kyclog = [select Id, createLegalEntityResponseStatusCode__c, createLegalEntityResponseStatusMessage__c, createLegalEntityResponseXml__c, name from litleRequestResponseLog__c where Log_Source__c ='KYC Request'];
    	System.assertEquals(1, kyclog.size());
    	System.assertEquals(String.valueOf(LitleErrorResponse.STATUS_CODE), kyclog.get(0).createLegalEntityResponseStatusCode__c);
    	System.assertEquals(LitleErrorResponse.STATUS_MESSAGE, kyclog.get(0).createLegalEntityResponseStatusMessage__c);
    	System.assertEquals(LitleErrorResponse.response, kyclog.get(0).createLegalEntityResponseXml__c);
    	litleKYCs = [select Id, Name from Litle_KYC__c];
        System.assertEquals(0, litleKYCs.size());         
        Test.stopTest(); 	   	
    }
    
    static testMethod void fetchKycForAccountFromMP_Success(){
    	LitleKYCService litleKYCService = new LitleKYCService();
 		Account account = new Account(name=ACCOUNT_NAME, LitleLegalEntityId__c = 'testLitleLegalEntityId__c');
        insert account;
        SalesforceLitleMappingsObject__c mappingObject = new SalesforceLitleMappingsObject__c();
        mappingObject.MerchantUsername__c = 'testUsername';
        mappingObject.MerchantPassword__c = 'testPassword';
        mappingObject.LitleEnvironment__c = 'CERT';
        insert mappingObject;
		List<litleRequestResponseLog__c> kyclog = [select Id, createLegalEntityResponseStatusCode__c, createLegalEntityResponseStatusMessage__c, createLegalEntityResponseXml__c, name from litleRequestResponseLog__c where Log_Source__c ='KYC Request'];
    	System.assertEquals(0, kyclog.size());
    	List<Litle_KYC__c> litleKYCs = [select Id, Name from Litle_KYC__c];
        System.assertEquals(0, litleKYCs.size()); 
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(new LegalEntityApprovedResponse(false), null));       
 		litleKYCService.fetchKycForAccountFromMP(account);       	
        kyclog = [select Id,createLegalEntityResponseStatusCode__c, createLegalEntityResponseStatusMessage__c, createLegalEntityResponseXml__c, name from litleRequestResponseLog__c where Log_Source__c ='KYC Request'];
    	System.assertEquals(1, kyclog.size());
    	System.assertEquals(String.valueOf(LegalEntityApprovedResponse.STATUS_CODE), kyclog.get(0).createLegalEntityResponseStatusCode__c);
    	System.assertEquals(LegalEntityApprovedResponse.STATUS_MESSAGE, kyclog.get(0).createLegalEntityResponseStatusMessage__c);
    	System.assertEquals(LegalEntityApprovedResponse.approvedResponse, kyclog.get(0).createLegalEntityResponseXml__c);
    	litleKYCs = [select Id, Name from Litle_KYC__c];
        System.assertEquals(1, litleKYCs.size());    
        Test.stopTest();   	
    }
}