salesforce-litle-MP/src/objects/SalesforceLitleMappingsObject__c.object
<CustomObject>
    <description>Salesforce and Litle&apos;s field mappings object</description>
    <fields>
        <fullName>legalEntityAnnualCreditCardSalesVolume__c</fullName>
        <description>Legal Entity AnnualCreditCardSalesVolume</description>
        <label>legalEntityAnnualCreditCardSalesVolume</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityCity__c</fullName>
        <description>Legal Entity City</description>
        <label>legalEntityCity</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityContactPhone__c</fullName>
        <description>Legal Entity ContactPhone</description>
        <label>legalEntityContactPhone</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityCountryCode__c</fullName>
        <description>Legal Entity CountryCode</description>
        <label>legalEntityCountryCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityDoingBusinessAs__c</fullName>
        <description>Legal Entity DoingBusinessAs</description>
        <label>legalEntityDoingBusinessAs</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityHasAcceptedCreditCards__c</fullName>
        <description>Legal Entity HasAcceptedCreditCards</description>
        <label>legalEntityHasAcceptedCreditCards</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityIsExclusiveToPsp__c</fullName>
        <description>Legal Entity IsExclusiveToPsp</description>
        <label>legalEntityIsExclusiveToPsp</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityIsPciComplianceValidated__c</fullName>
        <description>Legal Entity IsPciComplianceValidated</description>
        <label>legalEntityIsPciComplianceValidated</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityMostRecentlyPassedScan__c</fullName>
        <description>Legal Entity MostRecentlyPassedScan</description>
        <label>legalEntityMostRecentlyPassedScan</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityName__c</fullName>
        <description>Legal Entity Name</description>
        <label>legalEntityName</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPciLevel__c</fullName>
        <description>Legal Entity PciLevel</description>
        <label>legalEntityPciLevel</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPostalCode__c</fullName>
        <description>Legal Entity PostalCode</description>
        <label>legalEntityPostalCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalCity__c</fullName>
        <description>Legal Entity City</description>
        <label>legalEntityPrincipalCity</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalContactPhone__c</fullName>
        <description>Legal Entity ContactPhone</description>
        <label>legalEntityPrincipalContactPhone</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalCountryCode__c</fullName>
        <description>Legal Entity CountryCode</description>
        <label>legalEntityPrincipalCountryCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalDateOfBirth__c</fullName>
        <description>Legal Entity Principal DateOfBirth</description>
        <label>legalEntityPrincipalDateOfBirth</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalDriversLicenseState__c</fullName>
        <description>Legal Entity Principal DriversLicenseState</description>
        <label>legalEntityPrincipalDriversLicenseState</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalDriversLicense__c</fullName>
        <description>Legal Entity Principal DriversLicense</description>
        <label>legalEntityPrincipalDriversLicense</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalEmailAddress__c</fullName>
        <description>Legal Entity Principal EmailAddress</description>
        <label>legalEntityPrincipalEmailAddress</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalFirstName__c</fullName>
        <description>Legal Entity Principal FirstName</description>
        <label>legalEntityPrincipalFirstName</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalLastName__c</fullName>
        <description>Legal Entity Principal LastName</description>
        <label>legalEntityPrincipalLastName</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalPostalCode__c</fullName>
        <description>Legal Entity PostalCode</description>
        <label>legalEntityPrincipalPostalCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalSsn__c</fullName>
        <description>Legal Entity Principal Ssn</description>
        <label>legalEntityPrincipalSsn</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalStateProvince__c</fullName>
        <description>Legal Entity StateProvince</description>
        <label>legalEntityPrincipalStateProvince</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalStreetAddress1__c</fullName>
        <description>Legal Entity StreetAddress1</description>
        <label>legalEntityPrincipalStreetAddress1</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityPrincipalStreetAddress2__c</fullName>
        <description>Legal Entity StreetAddress2</description>
        <label>legalEntityPrincipalStreetAddress2</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityQualifiedSecurityAssessor__c</fullName>
        <description>Legal Entity QualifiedSecurityAssessor</description>
        <label>legalEntityQualifiedSecurityAssessor</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityReportOnCompliance__c</fullName>
        <description>Legal Entity ReportOnCompliance</description>
        <label>legalEntityReportOnCompliance</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityScanningVendor__c</fullName>
        <description>Legal Entity ScanningVendor</description>
        <label>legalEntityScanningVendor</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityStateProvince__c</fullName>
        <description>Legal Entity StateProvince</description>
        <label>legalEntityStateProvince</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityStreetAddress1__c</fullName>
        <description>Legal Entity StreetAddress1</description>
        <label>legalEntityStreetAddress1</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityStreetAddress2__c</fullName>
        <description>Legal Entity StreetAddress2</description>
        <label>legalEntityStreetAddress2</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>legalEntityTaxId__c</fullName>
        <description>Legal Entity TaxId</description>
        <label>legalEntityTaxId</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantAmexMid__c</fullName>
        <description>Sub Merchant AmexMid</description>
        <label>subMerchantAmexMid</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantBankAccountNumber__c</fullName>
        <description>Sub Merchant BankAccountNumber</description>
        <label>subMerchantBankAccountNumber</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantBankRoutingNumber__c</fullName>
        <description>Sub Merchant BankRoutingNumber</description>
        <label>subMerchantBankRoutingNumber</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantCity__c</fullName>
        <description>Sub Merchant City</description>
        <label>subMerchantCity</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantCountryCode__c</fullName>
        <description>Sub Merchant CountryCode</description>
        <label>subMerchantCountryCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantCreateCredentials__c</fullName>
        <description>Sub Merchant CreateCredentials</description>
        <label>subMerchantCreateCredentials</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantCustomerServiceNumber__c</fullName>
        <description>Sub Merchant CustomerServiceNumber</description>
        <label>subMerchantCustomerServiceNumber</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantDiscoverConveyMid__c</fullName>
        <description>Sub Merchant DiscoverConveyMid</description>
        <label>subMerchantDiscoverConveyMid</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantEmailAddress__c</fullName>
        <description>Sub Merchant EmailAddress</description>
        <label>subMerchantEmailAddress</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantFirstName__c</fullName>
        <description>Sub Merchant FirstName</description>
        <label>subMerchantFirstName</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantHardCodeBillingDescriptor__c</fullName>
        <description>Sub Merchant HardCodeBillingDescriptor</description>
        <label>subMerchantHardCodeBillingDescriptor</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantLastName__c</fullName>
        <description>Sub Merchant LastName</description>
        <label>subMerchantLastName</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantMaxTransactionAmount__c</fullName>
        <description>Sub Merchant MaxTransactionAmount</description>
        <label>subMerchantMaxTransactionAmount</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantMerchantCategoryCode__c</fullName>
        <description>Sub Merchant MerchantCategoryCode</description>
        <label>subMerchantMerchantCategoryCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantMerchantName__c</fullName>
        <description>Sub Merchant MerchantName</description>
        <label>subMerchantMerchantName</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantPhone__c</fullName>
        <description>Sub Merchant Phone</description>
        <label>subMerchantPhone</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantPostalCode__c</fullName>
        <description>Sub Merchant PostalCode</description>
        <label>subMerchantPostalCode</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantPspMerchantId__c</fullName>
        <description>Sub Merchant PspMerchantId</description>
        <label>subMerchantPspMerchantId</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantStateProvince__c</fullName>
        <description>Sub Merchant StateProvince</description>
        <label>subMerchantStateProvince</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantStreetAddress1__c</fullName>
        <description>Sub Merchant StreetAddress1</description>
        <label>subMerchantStreetAddress1</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantStreetAddress2__c</fullName>
        <description>Sub Merchant StreetAddress2</description>
        <label>subMerchantStreetAddress2</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchantUrl__c</fullName>
        <description>Sub Merchant Url</description>
        <label>subMerchantUrl</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchanteCheckBillingDescriptor__c</fullName>
        <description>Sub Merchant eCheckBillingDescriptor</description>
        <label>subMerchanteCheckBillingDescriptor</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>subMerchanteCheckCompanyName__c</fullName>
        <description>Sub Merchant eCheckCompanyName</description>
        <label>subMerchanteCheckCompanyName</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <label>SalesforceLitleMappingsObject</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Mapping Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SalesforceLitleMappingsObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce-litle-MP/src/classes/MappingObjectUtil.cls
public class MappingObjectUtil {
	
	//returns true if the given mapping object has the any mapping of the given
	//sobject type
	public static Boolean isSobjectTypePresentInMapping(SalesforceLitleMappingsObject__c mappingObject, String sObjectType){
		if(mappingObject != null && String.isNotEmpty(sObjectType)){
			if(String.isNotEmpty(mappingObject.legalEntityAnnualCreditCardSalesVolume__c) && mappingObject.legalEntityAnnualCreditCardSalesVolume__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityCity__c) && mappingObject.legalEntityCity__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityContactPhone__c) && mappingObject.legalEntityContactPhone__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityCountryCode__c) && mappingObject.legalEntityCountryCode__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityDoingBusinessAs__c) && mappingObject.legalEntityDoingBusinessAs__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPrincipalEmailAddress__c) && mappingObject.legalEntityPrincipalEmailAddress__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityHasAcceptedCreditCards__c) && mappingObject.legalEntityHasAcceptedCreditCards__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityIsExclusiveToPsp__c) && mappingObject.legalEntityIsExclusiveToPsp__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityIsPciComplianceValidated__c) && mappingObject.legalEntityIsPciComplianceValidated__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityMostRecentlyPassedScan__c) && mappingObject.legalEntityMostRecentlyPassedScan__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityName__c) && mappingObject.legalEntityName__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPciLevel__c) && mappingObject.legalEntityPciLevel__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPostalCode__c) && mappingObject.legalEntityPostalCode__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPrincipalDateOfBirth__c) && mappingObject.legalEntityPrincipalDateOfBirth__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPrincipalDriversLicense__c) && mappingObject.legalEntityPrincipalDriversLicense__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPrincipalDriversLicenseState__c) && mappingObject.legalEntityPrincipalDriversLicenseState__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPrincipalFirstName__c) && mappingObject.legalEntityPrincipalFirstName__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPrincipalLastName__c) && mappingObject.legalEntityPrincipalLastName__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPrincipalSsn__c) && mappingObject.legalEntityPrincipalSsn__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPrincipalContactPhone__c) && mappingObject.legalEntityPrincipalContactPhone__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPrincipalCity__c) && mappingObject.legalEntityPrincipalCity__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPrincipalCountryCode__c) && mappingObject.legalEntityPrincipalCountryCode__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPrincipalPostalCode__c) && mappingObject.legalEntityPrincipalPostalCode__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPrincipalStateProvince__c) && mappingObject.legalEntityPrincipalStateProvince__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPrincipalStreetAddress1__c) && mappingObject.legalEntityPrincipalStreetAddress1__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityPrincipalStreetAddress2__c) && mappingObject.legalEntityPrincipalStreetAddress2__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityQualifiedSecurityAssessor__c) && mappingObject.legalEntityQualifiedSecurityAssessor__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityReportOnCompliance__c) && mappingObject.legalEntityReportOnCompliance__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityScanningVendor__c) && mappingObject.legalEntityScanningVendor__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityStateProvince__c) && mappingObject.legalEntityStateProvince__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityStreetAddress1__c) && mappingObject.legalEntityStreetAddress1__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityStreetAddress2__c) && mappingObject.legalEntityStreetAddress2__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.legalEntityTaxId__c) && mappingObject.legalEntityTaxId__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantAmexMid__c) && mappingObject.subMerchantAmexMid__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantBankAccountNumber__c) && mappingObject.subMerchantBankAccountNumber__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantBankRoutingNumber__c) && mappingObject.subMerchantBankRoutingNumber__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantCity__c) && mappingObject.subMerchantCity__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantCountryCode__c) && mappingObject.subMerchantCountryCode__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantCreateCredentials__c) && mappingObject.subMerchantCreateCredentials__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantCustomerServiceNumber__c) && mappingObject.subMerchantCustomerServiceNumber__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantDiscoverConveyMid__c) && mappingObject.subMerchantDiscoverConveyMid__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchanteCheckBillingDescriptor__c) && mappingObject.subMerchanteCheckBillingDescriptor__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchanteCheckCompanyName__c) && mappingObject.subMerchanteCheckCompanyName__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantEmailAddress__c) && mappingObject.subMerchantEmailAddress__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantFirstName__c) && mappingObject.subMerchantFirstName__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantHardCodeBillingDescriptor__c) && mappingObject.subMerchantHardCodeBillingDescriptor__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantLastName__c) && mappingObject.subMerchantLastName__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantMaxTransactionAmount__c) && mappingObject.subMerchantMaxTransactionAmount__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantMerchantCategoryCode__c) && mappingObject.subMerchantMerchantCategoryCode__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantMerchantName__c) && mappingObject.subMerchantMerchantName__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantPhone__c) && mappingObject.subMerchantPhone__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantPostalCode__c) && mappingObject.subMerchantPostalCode__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantPspMerchantId__c) && mappingObject.subMerchantPspMerchantId__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantStateProvince__c) && mappingObject.subMerchantStateProvince__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantStreetAddress1__c) && mappingObject.subMerchantStreetAddress1__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantStreetAddress2__c) && mappingObject.subMerchantStreetAddress2__c.startsWith(sObjectType)) {
				return true;
			}
			if(String.isNotEmpty(mappingObject.subMerchantUrl__c) && mappingObject.subMerchantUrl__c.startsWith(sObjectType)) {
				return true;
			}
		}
		return false;
				
	}

}